import type { SiteLanguage } from './i18n';

export type GlossaryCategory = 'BMKG' | 'NASA';

export type GlossaryTerm = {
  id: string;
  category: GlossaryCategory;
  term: Record<SiteLanguage, string>;
  definition: Record<SiteLanguage, string>;
  example: Record<SiteLanguage, string>;
  image: string;
  source: string;
  updatedAt: string;
  articles?: Partial<Record<SiteLanguage, string>>;
  translatedLocales?: Partial<Record<SiteLanguage, boolean>>;
};

const updatedAt = '2026-06-27T00:00:00.000Z';

const bmkgTerms = [
  ['hujan-ringan', 'Hujan Ringan', 'Light Rain', 'Hujan Ringan', '小雨', '小雨', 'Curah hujan rendah yang biasanya tidak mengganggu aktivitas besar, tetapi tetap membuat permukaan jalan licin.', 'Contoh: BMKG memprakirakan hujan ringan pada sore hari.'],
  ['hujan-sedang', 'Hujan Sedang', 'Moderate Rain', 'Hujan Sederhana', '中雨', '中程度の雨', 'Hujan dengan intensitas menengah yang dapat mengurangi jarak pandang dan membuat drainase kota bekerja lebih berat.', 'Contoh: pengendara perlu memperlambat laju saat hujan sedang.'],
  ['hujan-lebat', 'Hujan Lebat', 'Heavy Rain', 'Hujan Lebat', '大雨', '大雨', 'Curah hujan tinggi dalam waktu singkat atau lama yang dapat memicu genangan, banjir, atau longsor di daerah rawan.', 'Contoh: peringatan dini hujan lebat berlaku malam ini.'],
  ['hujan-rintik', 'Hujan Rintik-rintik', 'Drizzle', 'Gerimis', '毛毛雨', '小雨/霧雨', 'Tetes hujan sangat kecil yang turun rapat, sering terasa seperti kabut basah di udara.', 'Contoh: kosame adalah sebutan Jepang untuk hujan rintik yang lembut.'],
  ['awan-cumulonimbus', 'Awan Cumulonimbus', 'Cumulonimbus Cloud', 'Awan Kumulonimbus', '积雨云', '積乱雲', 'Awan vertikal besar yang sering berkaitan dengan hujan lebat, petir, angin kencang, dan cuaca ekstrem.', 'Contoh: pilot menghindari awan cumulonimbus karena turbulensinya kuat.'],
  ['angin-kencang', 'Angin Kencang', 'Strong Wind', 'Angin Kencang', '强风', '強風', 'Gerakan udara berkecepatan tinggi yang dapat merusak atap, pohon, baliho, dan mengganggu pelayaran.', 'Contoh: nelayan menunda melaut saat peringatan angin kencang aktif.'],
  ['gelombang-tinggi', 'Gelombang Tinggi', 'High Wave', 'Gelombang Tinggi', '高浪', '高波', 'Kondisi laut dengan tinggi gelombang berbahaya bagi kapal kecil, wisata pantai, dan aktivitas pelabuhan.', 'Contoh: BMKG mengimbau kapal kecil mewaspadai gelombang tinggi.'],
  ['suhu-maksimum', 'Suhu Maksimum', 'Maximum Temperature', 'Suhu Maksimum', '最高气温', '最高気温', 'Suhu udara tertinggi yang tercatat dalam rentang waktu tertentu, umumnya satu hari.', 'Contoh: suhu maksimum Jakarta hari ini mencapai 34 derajat Celsius.'],
  ['kelembapan', 'Kelembapan Udara', 'Humidity', 'Kelembapan Udara', '湿度', '湿度', 'Jumlah uap air di udara yang memengaruhi rasa gerah, pembentukan awan, dan potensi hujan.', 'Contoh: kelembapan tinggi membuat suhu terasa lebih panas.'],
  ['tekanan-udara', 'Tekanan Udara', 'Air Pressure', 'Tekanan Udara', '气压', '気圧', 'Gaya udara pada permukaan bumi yang membantu menjelaskan pola angin dan perubahan cuaca.', 'Contoh: tekanan udara menurun dapat menandai sistem cuaca aktif.'],
  ['gempa-tektonik', 'Gempa Tektonik', 'Tectonic Earthquake', 'Gempa Tektonik', '构造地震', '地殻変動性地震', 'Gempa yang terjadi akibat pelepasan energi dari pergerakan lempeng tektonik.', 'Contoh: gempa tektonik kuat dapat memicu tsunami jika pusatnya berada di laut.'],
  ['magnitudo', 'Magnitudo', 'Magnitude', 'Magnitud', '震级', 'マグニチュード', 'Ukuran energi gempa yang dilepaskan dari sumbernya, bukan ukuran kerusakan di permukaan.', 'Contoh: magnitudo 5 tidak selalu berarti dampaknya sama di semua tempat.'],
  ['episenter', 'Episenter', 'Epicenter', 'Episentrum', '震中', '震央', 'Titik di permukaan bumi yang berada tepat di atas pusat gempa.', 'Contoh: episenter gempa berada 80 km barat daya kota.'],
  ['hiposenter', 'Hiposenter', 'Hypocenter', 'Hypocentrum', '震源', '震源', 'Titik di dalam bumi tempat gempa bermula dan energi dilepaskan.', 'Contoh: hiposenter dangkal sering terasa lebih kuat di permukaan.'],
  ['tsunami', 'Tsunami', 'Tsunami', 'Tsunami', '海啸', '津波', 'Gelombang laut panjang yang dapat dipicu gempa bawah laut, longsoran, atau letusan gunung api.', 'Contoh: peringatan dini tsunami harus diikuti dengan evakuasi cepat.'],
  ['pmm', 'Prakiraan Musim', 'Seasonal Forecast', 'Ramalan Musim', '季节预报', '季節予報', 'Informasi peluang awal musim hujan atau kemarau berdasarkan analisis atmosfer dan laut.', 'Contoh: prakiraan musim membantu petani menentukan waktu tanam.'],
  ['el-nino', 'El Nino', 'El Nino', 'El Nino', '厄尔尼诺', 'エルニーニョ', 'Pemanasan suhu muka laut Pasifik tengah-timur yang dapat mengurangi curah hujan di sebagian Indonesia.', 'Contoh: El Nino kuat sering berkaitan dengan kemarau lebih kering.'],
  ['la-nina', 'La Nina', 'La Nina', 'La Nina', '拉尼娜', 'ラニーニャ', 'Pendinginan suhu muka laut Pasifik tengah-timur yang dapat meningkatkan peluang hujan di Indonesia.', 'Contoh: La Nina bisa membuat musim hujan lebih basah.'],
  ['mjo', 'Madden-Julian Oscillation', 'Madden-Julian Oscillation', 'Ayunan Madden-Julian', '马登-朱利安振荡', 'マッデン・ジュリアン振動', 'Gelombang atmosfer tropis yang bergerak ke timur dan dapat meningkatkan pembentukan awan hujan.', 'Contoh: fase MJO aktif sering memperkuat hujan di wilayah Indonesia.'],
  ['indeks-uv', 'Indeks UV', 'UV Index', 'Indeks UV', '紫外线指数', 'UV指数', 'Skala risiko paparan radiasi ultraviolet matahari terhadap kulit dan mata.', 'Contoh: indeks UV ekstrem memerlukan topi, tabir surya, dan pembatasan aktivitas luar ruang.'],
  ['jarak-pandang', 'Jarak Pandang', 'Visibility', 'Jarak Penglihatan', '能见度', '視程', 'Jarak maksimum objek masih dapat terlihat jelas, penting untuk penerbangan, pelayaran, dan lalu lintas.', 'Contoh: kabut tebal menurunkan jarak pandang di bandara.'],
  ['puting-beliung', 'Puting Beliung', 'Waterspout/Tornado-like Vortex', 'Puting Beliung', '龙卷风状旋涡', '竜巻状の渦', 'Pusaran angin lokal berdurasi singkat yang dapat merusak bangunan ringan dan pohon.', 'Contoh: awan gelap menjulang bisa mendahului puting beliung.'],
  ['cuaca-ekstrem', 'Cuaca Ekstrem', 'Extreme Weather', 'Cuaca Ekstrem', '极端天气', '極端気象', 'Kondisi cuaca yang berpotensi menimbulkan bahaya, seperti hujan sangat lebat, angin kencang, atau petir intens.', 'Contoh: notifikasi cuaca ekstrem dikirim untuk mengurangi risiko warga.'],
  ['petir', 'Petir', 'Lightning', 'Kilat', '闪电', '雷', 'Pelepasan listrik di atmosfer yang sering menyertai awan badai dan hujan lebat.', 'Contoh: hindari lapangan terbuka saat petir sering terjadi.'],
];

const nasaTerms = [
  ['apod', 'APOD', 'Astronomy Picture of the Day', 'Gambar Astronomi Harian', '每日天文图', '今日の天文画像', 'Program NASA yang menerbitkan gambar atau video astronomi pilihan setiap hari beserta penjelasan ilmiah.', 'Contoh: APOD hari ini menampilkan nebula yang dipotret teleskop luar angkasa.'],
  ['neo', 'NEO', 'Near-Earth Object', 'Objek Dekat Bumi', '近地天体', '地球近傍天体', 'Asteroid atau komet yang orbitnya membawa objek tersebut cukup dekat dengan orbit Bumi.', 'Contoh: sistem NeoWs memantau banyak NEO setiap hari.'],
  ['neos', 'NeoWs', 'Near Earth Object Web Service', 'Perkhidmatan Web Objek Dekat Bumi', '近地天体网络服务', '地球近傍天体Webサービス', 'API NASA untuk membaca daftar objek dekat Bumi, jarak lintasan, ukuran, dan status potensi bahayanya.', 'Contoh: cron komet memakai NeoWs secara terbatas dari server.'],
  ['aphelion', 'Aphelion', 'Aphelion', 'Afelion', '远日点', '遠日点', 'Titik orbit benda langit ketika berada paling jauh dari Matahari.', 'Contoh: komet bergerak lebih lambat saat mendekati aphelion.'],
  ['perihelion', 'Perihelion', 'Perihelion', 'Perihelion', '近日点', '近日点', 'Titik orbit benda langit ketika berada paling dekat dengan Matahari.', 'Contoh: komet sering tampak lebih aktif saat mendekati perihelion.'],
  ['asteroid', 'Asteroid', 'Asteroid', 'Asteroid', '小行星', '小惑星', 'Benda batuan kecil yang mengorbit Matahari, banyak ditemukan di sabuk asteroid antara Mars dan Jupiter.', 'Contoh: asteroid besar dapat memiliki bentuk tidak beraturan.'],
  ['comet', 'Komet', 'Comet', 'Komet', '彗星', '彗星', 'Benda es dan debu yang dapat membentuk koma dan ekor saat dipanaskan Matahari.', 'Contoh: ekor komet selalu terdorong menjauhi Matahari oleh angin surya.'],
  ['meteor', 'Meteor', 'Meteor', 'Meteor', '流星', '流星', 'Cahaya singkat yang tampak ketika meteoroid memasuki atmosfer dan terbakar.', 'Contoh: orang sering menyebut meteor sebagai bintang jatuh.'],
  ['meteorite', 'Meteorit', 'Meteorite', 'Meteorit', '陨石', '隕石', 'Sisa meteoroid yang berhasil mencapai permukaan Bumi.', 'Contoh: meteorit besi biasanya terasa lebih berat daripada batu biasa.'],
  ['meteoroid', 'Meteoroid', 'Meteoroid', 'Meteoroid', '流星体', '流星物質', 'Fragmen kecil batuan atau logam di ruang antarplanet sebelum memasuki atmosfer.', 'Contoh: meteoroid bisa berasal dari pecahan asteroid atau komet.'],
  ['rover', 'Rover', 'Rover', 'Rover', '巡视器', 'ローバー', 'Kendaraan robotik yang menjelajah permukaan planet atau bulan untuk mengambil gambar dan data ilmiah.', 'Contoh: Perseverance adalah rover NASA di Mars.'],
  ['sol', 'Sol Mars', 'Martian Sol', 'Sol Marikh', '火星日', '火星日', 'Satu hari di Mars, berdurasi sekitar 24 jam 39 menit waktu Bumi.', 'Contoh: foto rover sering diberi label berdasarkan sol pengambilan.'],
  ['spectrometer', 'Spektrometer', 'Spectrometer', 'Spektrometer', '光谱仪', '分光計', 'Instrumen untuk menganalisis cahaya atau radiasi agar komposisi suatu objek dapat dipelajari.', 'Contoh: spektrometer membantu mengenali mineral pada batuan Mars.'],
  ['regolith', 'Regolit', 'Regolith', 'Regolit', '风化层', 'レゴリス', 'Lapisan debu dan pecahan batuan lepas di permukaan Bulan, Mars, atau asteroid.', 'Contoh: jejak rover tampak jelas di regolit Mars.'],
  ['eclipse', 'Gerhana', 'Eclipse', 'Gerhana', '食', '食', 'Peristiwa ketika satu benda langit menutupi cahaya benda lain dari sudut pandang pengamat.', 'Contoh: gerhana Matahari terjadi saat Bulan berada di antara Bumi dan Matahari.'],
  ['aurora', 'Aurora', 'Aurora', 'Aurora', '极光', 'オーロラ', 'Cahaya di langit kutub akibat partikel bermuatan dari Matahari berinteraksi dengan atmosfer Bumi.', 'Contoh: badai geomagnetik kuat dapat memperluas wilayah aurora.'],
  ['solar-flare', 'Suar Matahari', 'Solar Flare', 'Suar Suria', '太阳耀斑', '太陽フレア', 'Letupan energi di atmosfer Matahari yang dapat memengaruhi komunikasi radio dan cuaca antariksa.', 'Contoh: suar Matahari kelas X termasuk kategori kuat.'],
  ['cme', 'CME', 'Coronal Mass Ejection', 'Lontaran Jisim Korona', '日冕物质抛射', 'コロナ質量放出', 'Lontaran plasma dan medan magnet dari korona Matahari ke ruang antarplanet.', 'Contoh: CME yang mengarah ke Bumi bisa memicu badai geomagnetik.'],
  ['light-year', 'Tahun Cahaya', 'Light-Year', 'Tahun Cahaya', '光年', '光年', 'Jarak yang ditempuh cahaya dalam satu tahun, bukan ukuran waktu harian.', 'Contoh: bintang terdekat selain Matahari berjarak lebih dari empat tahun cahaya.'],
  ['nebula', 'Nebula', 'Nebula', 'Nebula', '星云', '星雲', 'Awan gas dan debu antarbintang yang bisa menjadi tempat kelahiran bintang.', 'Contoh: Nebula Orion dapat dilihat dengan teleskop kecil.'],
  ['exoplanet', 'Eksoplanet', 'Exoplanet', 'Eksoplanet', '系外行星', '太陽系外惑星', 'Planet yang mengorbit bintang selain Matahari.', 'Contoh: teleskop ruang angkasa mencari eksoplanet dengan metode transit.'],
  ['transit', 'Transit Planet', 'Planetary Transit', 'Transit Planet', '行星凌日', '惑星トランジット', 'Peristiwa saat planet lewat di depan bintang dan sedikit meredupkan cahayanya.', 'Contoh: transit dipakai untuk menemukan banyak eksoplanet.'],
  ['escape-velocity', 'Kecepatan Lepas', 'Escape Velocity', 'Halaju Lepas', '逃逸速度', '脱出速度', 'Kecepatan minimum agar objek dapat lepas dari tarikan gravitasi benda langit.', 'Contoh: roket harus melampaui kecepatan lepas untuk meninggalkan Bumi.'],
  ['microgravity', 'Mikrogravitasi', 'Microgravity', 'Microgravity', '微重力', '微小重力', 'Kondisi ketika benda tampak hampir tanpa berat, seperti di orbit rendah Bumi.', 'Contoh: astronot melakukan eksperimen mikrogravitasi di ISS.'],
];

const glossaryDefsRu: Record<string, string> = {
  "Light Rain": "Лёгкий дождь: Обычный дождь, который обычно не мешает значительной активности, но все же делает дороги скользкими.",
  "Moderate Rain": "Умеренный дождь: Дождь средней интенсивности, который может снизить видимость и сделать работу системы дренажа города более сложной.",
  "Heavy Rain": "Тяжёлый дождь: Высокая интенсивность дождя в течение короткого или длительного периода времени, которая может привести к наводнениям, оползням или паводкам в зонах риска.",
  "Drizzle": "Дождь: Мелкие капли дождя, которые падают плотно, часто ощущаются как влажный туман в воздухе.",
  "Cumulonimbus Cloud": "Атмосферный фронт: Большие вертикальные облака, часто связанные с сильным дождем, грозами, сильным ветром и экстремальными погодными условиями.",
  "Strong Wind": "Сильный ветер: Быстрое движение воздуха, которое может повредить крыши, деревья, рекламные щиты и нарушить судоходство.",
  "High Wave": "Высокая волна: Состояние моря с опасными для малых судов, пляжных туристов и портовой деятельности.",
  "Maximum Temperature": "Максимальная температура: Наивысшая температура воздуха, зафиксированная в определённом временном интервале, обычно в течение одного дня.",
  "Humidity": "Влажность: Количество водяного пара в воздухе, которое влияет на ощущение жары, образование облаков и потенциал дождя.",
  "Air Pressure": "Воздушное давление: Сила воздуха на поверхности Земли, которая помогает объяснить закономерности ветра и изменения погоды.",
  "Tectonic Earthquake": "Тектоническое землетрясение: Землетрясение, которое происходит в результате освобождения энергии из-за движения тектонических плит.",
  "Magnitude": "Магнитуда: Размер энергии землетрясения, освобождаемой из источника, а не размер разрушений на поверхности.",
  "Epicenter": "Эпицентр: Точка на поверхности Земли, находящаяся прямо над центром землетрясения.",
  "Hypocenter": "Гипоцентр: Точка внутри Земли, где начинается землетрясение и освобождается энергия.",
  "Tsunami": "Цунами: Длинная волна в море, которая может быть вызвана землетрясением под водой, оползнем или извержением вулкана.",
  "Seasonal Forecast": "Сезонный прогноз: Информация о вероятности начала сезона дождей или засухи на основе анализа атмосферы и моря.",
  "El Nino": "Эль-Нино: Повышение температуры поверхности Тихого океана в центральной части, которое может снизить количество осадков в части Индонезии.",
  "La Nina": "Ла-Нина: Понижение температуры поверхности Тихого океана в центральной части, которое может повысить вероятность осадков в Индонезии.",
  "Madden-Julian Oscillation": "Мадден-Юлианская осцилляция: Тропическая атмосферная волна, которая движется на восток и может повысить образование облаков с осадками.",
  "UV Index": "Индекс УФ-излучения: Шкала риска воздействия ультрафиолетового излучения солнца на кожу и глаза.",
  "Visibility": "Видимость: Максимальная дистанция, на которой объект можно видеть ясно, важна для полётов, судоходства и дорожного движения.",
  "Waterspout/Tornado-like Vortex": "Пусарный шторм/тornado-подобный вихрь: Кратковременная местная вихряная струя, которая может повредить легкие постройки и деревья.",
  "Extreme Weather": "Экстремальная погода: Погодные условия, которые потенциально могут вызвать опасность, такие как сильный дождь, сильный ветер или интенсивные грозы.",
  "Lightning": "Молния: Выделение электричества в атмосфере, которое часто сопровождается тучами с сильным дождем и грозами.",
  "Astronomy Picture of the Day": "Астрономическая фотография дня: Программа NASA, которая публикует астрономическую фотографию или видео дня с научным комментарием.",
  "Near-Earth Object": "Астероид или комета, орбита которого приводит к тому, что объект находится достаточно близко к орбите Земли.",
  "Near Earth Object Web Service": "API NASA для чтения списка объектов, находящихся близко к Земле, расстояния орбиты, размеров и потенциальной опасности.",
  "Aphelion": "Точка орбиты небесного тела, когда оно находится на максимально большом расстоянии от Солнца.",
  "Perihelion": "Точка орбиты небесного тела, когда оно находится на максимально близком расстоянии к Солнцу.",
  "Asteroid": "Маленький каменный объект, который вращается вокруг Солнца, часто встречается в астероидном поясе между Марсом и Юпитером.",
  "Comet": "Объект из льда и пыли, который может образовывать кому и хвост при нагревании Солнцем.",
  "Meteor": "Кратковременное свечение, которое наблюдается, когда метеорит входит в атмосферу и сгорает.",
  "Meteorite": "Остаток метеорита, который смог достичь поверхности Земли.",
  "Meteoroid": "Маленький фрагмент камня или металла в межпланетном пространстве до входа в атмосферу.",
  "Rover": "Роботизированное транспортное средство, которое исследует поверхность планеты или луны для получения фотографий и научных данных.",
  "Martian Sol": "День на Марсе, длится примерно 24 часа 39 минут по времени Земли.",
  "Spectrometer": "Инструмент для анализа света или радиации, чтобы изучить состав объекта.",
  "Regolith": "Слои пыли и разрушенных камней на поверхности Луны, Марса или астероидов.",
  "Eclipse": "Событие, когда одно небесное тело закрывает свет другого небесного тела с точки зрения наблюдателя.",
  "Aurora": "Свет в полярных регионах, вызванный заряженными частицами от Солнца, взаимодействующими с атмосферой Земли.",
  "Solar Flare": "Взрыв энергии в атмосфере Солнца, который может повлиять на радиосвязь и космическую погоду.",
  "Coronal Mass Ejection": "Выделение плазмы и магнитного поля из короны Солнца в межпланетное пространство.",
  "Light-Year": "Расстояние, которое проходит свет за один год, а не ежедневная скорость.",
  "Nebula": "Пылевая шапка газа и пыли между звездами, которая может стать местом рождения звезд.",
  "Exoplanet": "Планета, вращающаяся вокруг другой звезды, кроме Солнца.",
  "Planetary Transit": "Событие, когда планета проходит перед звездой и слегка уменьшает ее свет.",
  "Escape Velocity": "Минимальная скорость, необходимая для того, чтобы объект мог выйти из гравитационного поля небесного тела.",
  "Microgravity": "Состояние, когда объект кажется почти без веса, как в низкой орбите Земли."
};

const glossaryDefsFr: Record<string, string> = {
  "Light Rain": "Pluie légère : une précipitation faible qui ne gêne généralement pas les activités, mais qui rend les routes glissantes.",
  "Moderate Rain": "Pluie modérée : une précipitation moyenne qui peut réduire la visibilité et rendre les systèmes d'évacuation urbains plus lourds de charge.",
  "Heavy Rain": "Pluie abondante : une précipitation forte et rapide qui peut provoquer des inondations, des glissements de terrain ou des crues dans les zones vulnérables.",
  "Drizzle": "Bruine : des gouttelettes d'eau très fines qui tombent abondamment, souvent ressenties comme un brouillard humide dans l'air.",
  "Cumulonimbus Cloud": "Nuage cumulonimbus : un nuage vertical important qui est souvent associé à la pluie forte, aux orages, aux vents violents et aux conditions météorologiques extrêmes.",
  "Strong Wind": "Vent fort : un mouvement d'air rapide qui peut endommager les toits, les arbres, les panneaux publicitaires et perturber la navigation.",
  "High Wave": "Houle élevée : une condition de la mer avec des vagues dangereuses pour les petits bateaux, les plages et les activités portuaires.",
  "Maximum Temperature": "Température maximale : la température la plus élevée enregistrée dans une période donnée, généralement une journée.",
  "Humidity": "Humidité : la quantité d'eau vapeur dans l'air qui affecte la sensation de chaleur, la formation des nuages et la probabilité de pluie.",
  "Air Pressure": "Pression atmosphérique : la force de l'air sur la surface terrestre qui aide à expliquer les modèles de vent et les changements météorologiques.",
  "Tectonic Earthquake": "Séisme tectonique : un tremblement de terre causé par la libération d'énergie due à la déformation des plaques tectoniques.",
  "Magnitude": "Magnitude : la mesure de l'énergie libérée par un séisme à son origine, et non la mesure des dommages sur la surface.",
  "Epicenter": "Épicentre : le point sur la surface de la Terre qui se trouve directement au-dessus du centre du séisme.",
  "Hypocenter": "Hypocentre : le point à l'intérieur de la Terre où le séisme a commencé et où l'énergie a été libérée.",
  "Tsunami": "Tsunami : une vague de la mer longue qui peut être déclenchée par un séisme sous-marin, un glissement de terrain ou une éruption volcanique.",
  "Seasonal Forecast": "Prévision saisonnière : des informations sur les probabilités de début de saison pluvieuse ou sèche basées sur l'analyse de l'atmosphère et de la mer.",
  "El Nino": "El Niño : une augmentation de la température de la surface de l'océan Pacifique oriental qui peut réduire les précipitations en partie de l'Indonésie.",
  "La Nina": "La Niña : une diminution de la température de la surface de l'océan Pacifique oriental qui peut augmenter les chances de précipitations en Indonésie.",
  "Madden-Julian Oscillation": "Oscillation de Madden-Julian : une onde atmosphérique tropicale qui se déplace vers l'est et peut augmenter la formation de nuages pluvieux.",
  "UV Index": "Indice UV : une échelle de risque de rayonnement ultraviolet solaire pour la peau et les yeux.",
  "Visibility": "Visibilité : la distance maximale à laquelle un objet peut être vu clairement, importante pour l'aviation, la navigation et la circulation routière.",
  "Waterspout/Tornado-like Vortex": "Pusarangeur : un tourbillon d'air local de courte durée qui peut endommager les bâtiments légers et les arbres.",
  "Extreme Weather": "Météo extrême : des conditions météorologiques qui peuvent causer des dommages, comme des pluies très fortes, des vents violents ou des éclairs intenses.",
  "Lightning": "Éclair : une libération d'électricité dans l'atmosphère qui est souvent associée à des nuages orageux et à des pluies fortes.",
  "Astronomy Picture of the Day": "Image astronomique du jour : un programme de la NASA qui publie une image ou un vidéo astronomique sélectionnée chaque jour avec une explication scientifique.",
  "Near-Earth Object": "Asteroid ou comète dont l'orbite amène l'objet suffisamment près de l'orbite de la Terre.",
  "Near Earth Object Web Service": "API NASA pour lire la liste des objets proches de la Terre, distance de la trajectoire, taille, et statut de la potentielle dangerosité.",
  "Aphelion": "Point d'orbite du corps céleste lorsque celui-ci se trouve le plus loin du Soleil.",
  "Perihelion": "Point d'orbite du corps céleste lorsque celui-ci se trouve le plus près du Soleil.",
  "Asteroid": "Corps rocheux petit qui orbite autour du Soleil, nombreux sont trouvés dans la ceinture d'astéroïdes entre Mars et Jupiter.",
  "Comet": "Corps de glace et de poussière qui peut former une queue et une coma lorsqu'il est chauffé par le Soleil.",
  "Meteor": "Éclair court qui apparaît lorsque le météorite entre dans l'atmosphère et se consume.",
  "Meteorite": "Résidu du météorite qui a réussi à atteindre la surface de la Terre.",
  "Meteoroid": "Fragment de roche ou de métal dans l'espace interplanétaire avant d'entrer dans l'atmosphère.",
  "Rover": "Véhicule robotique qui explore la surface d'une planète ou d'une lune pour prendre des photos et des données scientifiques.",
  "Martian Sol": "Un jour sur Mars, d'une durée d'environ 24 heures 39 minutes du temps terrestre.",
  "Spectrometer": "Instrument pour analyser la lumière ou la radiation afin de pouvoir étudier la composition d'un objet.",
  "Regolith": "Couche de poussière et de fragments de roches éparpillés sur la surface de la Lune, de Mars ou d'un astéroïde.",
  "Eclipse": "Événement lorsque l'un des corps célestes cache la lumière d'un autre corps céleste du point de vue d'un observateur.",
  "Aurora": "Lumière du ciel polaire due à l'interaction de particules chargées du Soleil avec l'atmosphère de la Terre.",
  "Solar Flare": "Explosion d'énergie dans l'atmosphère du Soleil qui peut affecter la communication radio et le temps météorologique spatial.",
  "Coronal Mass Ejection": "Départ de plasma et de champ magnétique de la couronne du Soleil dans l'espace interplanétaire.",
  "Light-Year": "Distance parcourue par la lumière en une année, pas une unité de temps quotidienne.",
  "Nebula": "Nuage de gaz et de poussière interstellaire qui peut devenir un lieu de naissance d'étoiles.",
  "Exoplanet": "Planète qui orbite autour d'une étoile autre que le Soleil.",
  "Planetary Transit": "Événement lorsque la planète passe devant l'étoile et légèrement diminue sa luminosité.",
  "Escape Velocity": "Vitesse minimale pour que l'objet puisse s'échapper de la gravité d'un corps céleste.",
  "Microgravity": "État dans lequel un objet semble presque sans poids, comme dans une orbite basse de la Terre."
};

const glossaryExsRu: Record<string, string> = {
  "Light Rain": "Пример: BMKG прогнозирует легкий дождь на вечер.",
  "Moderate Rain": "Пример: водители должны замедлить скорость во время умеренного дождя.",
  "Heavy Rain": "Пример: предупреждение о сильном дожде действует tonight.",
  "Drizzle": "Пример: косаме — это японское название для легкого дождя.",
  "Cumulonimbus Cloud": "Пример: пилоты избегают cumulonimbus-ов из-за их сильной турбулентности.",
  "Strong Wind": "Пример: рыбаки откладывают выход в море во время предупреждения о сильном ветре.",
  "High Wave": "Пример: BMKG предупреждает малые суда о высоких волнах.",
  "Maximum Temperature": "Пример: максимальная температура в Джакарте сегодня достигает 34 градуса Цельсия.",
  "Humidity": "Пример: высокая влажность делает температуру чувствоваться более жаркой.",
  "Air Pressure": "Пример: снижение атмосферного давления может указывать на активность погоды.",
  "Tectonic Earthquake": "Пример: сильное тектоническое землетрясение может спровоцировать цунами, если его эпицентр находится в море.",
  "Magnitude": "Пример: магнитуда 5 не всегда означает одинаковый эффект в разных местах.",
  "Epicenter": "Пример: эпицентр землетрясения находится в 80 км к юго-западу от города.",
  "Hypocenter": "Пример: гипоцентр浅 часто чувствуется сильнее на поверхности.",
  "Tsunami": "Пример: предупреждение о цунами должно сопровождаться быстрой эвакуацией.",
  "Seasonal Forecast": "Пример: прогноз сезона помогает фермерам решить, когда сажать.",
  "El Nino": "Пример: сильный Эль-Нино часто связан с более сухой засухой.",
  "La Nina": "Пример: Ла-Нина может сделать сезон дождей более влажным.",
  "Madden-Julian Oscillation": "Пример: активная фаза MJO часто усиливает дождь в Индонезии.",
  "UV Index": "Пример: экстремальный индекс УВ требует шляпы, солнцезащитного крема и ограничения внешней активности.",
  "Visibility": "Пример: густой туман снижает видимость на аэродроме.",
  "Waterspout/Tornado-like Vortex": "Пример: темная туча может предшествовать торнадо.",
  "Extreme Weather": "Пример: уведомление о экстремальной погоде отправляется для снижения риска для местного населения.",
  "Lightning": "Пример: избегайте открытых мест во время частых гроз.",
  "Astronomy Picture of the Day": "Пример: АПОД сегодня показывает фотографию космического телескопа, сделанную в космосе.",
  "Near-Earth Object": "Пример: система NeoWs отслеживает много NEO каждый день.",
  "Near Earth Object Web Service": "Пример: cron кометы использует NeoWs ограниченно с сервера.",
  "Aphelion": "Пример: комета движется медленнее, приближаясь к афелию.",
  "Perihelion": "Пример: комета часто выглядит более активной, приближаясь к перигелию.",
  "Asteroid": "Пример: большой астероид может иметь нерегулярную форму.",
  "Comet": "Пример: хвост кометы всегда толкается солнцем в сторону от Солнца солнечным ветром.",
  "Meteor": "Пример: люди часто называют метеор «падущей звездой».",
  "Meteorite": "Пример: железный метеорит обычно чувствуется тяжелее, чем обычная скала.",
  "Meteoroid": "Пример: метеорид может происходить от фрагмента астероида или кометы.",
  "Rover": "Пример: Perseverance — это марсоход NASA на Марсе.",
  "Martian Sol": "Пример: фотографии марсохода часто маркируются по солу, на котором они были сделаны.",
  "Spectrometer": "Пример: спектрометр помогает выявить минералы в марсианских скалах.",
  "Regolith": "Пример: следы марсохода видны четко на марсианском реголите.",
  "Eclipse": "Пример: солнечное затмение происходит, когда Луна находится между Землей и Солнцем.",
  "Aurora": "Пример: сильная геомагнитная буря может расширить область ауроры.",
  "Solar Flare": "Пример: солнечный взрыв класса X включает в себя сильную категорию.",
  "Coronal Mass Ejection": "Пример: CME, направленная к Земле, может спровоцировать геомагнитную бурю.",
  "Light-Year": "Пример: ближайшая звезда, кроме Солнца, находится на расстоянии более четырех световых лет.",
  "Nebula": "Пример: Небула Ориона можно увидеть с помощью небольшого телескопа.",
  "Exoplanet": "Пример: космический телескоп ищет экзопланеты с помощью метода транзита.",
  "Planetary Transit": "Пример: транзит используется для обнаружения многих экзопланет.",
  "Escape Velocity": "Пример: ракета должна преодолеть скорость бегства, чтобы покинуть Землю.",
  "Microgravity": "Пример: астронавты проводят эксперименты с микрогравитацией на МКС."
};

const glossaryExsFr: Record<string, string> = {
  "Pluie Faible": "Contoh: BMKG memprakirakan hujan ringan pada sore hari.",
  "Pluie Modérée": "Contoh: pengendara perlu memperlambat laju saat hujan sedang.",
  "Pluie Abondante": "Contoh: peringatan dini hujan lebat berlaku malam ini.",
  "Bruine": "Contoh: kosame adalah sebutan Jepang untuk hujan rintik yang lembut.",
  "Nuage de Cumulonimbus": "Contoh: pilot menghindari awan cumulonimbus karena turbulensinya kuat.",
  "Vent Fort": "Contoh: nelayan menunda melaut saat peringatan angin kencang aktif.",
  "Houle Élevée": "Contoh: BMKG mengimbau kapal kecil mewaspadai gelombang tinggi.",
  "Température Maximale": "Contoh: suhu maksimum Jakarta hari ini mencapai 34 derajat Celsius.",
  "Humidité": "Contoh: kelembapan tinggi membuat suhu terasa lebih panas.",
  "Pression Atmosphérique": "Contoh: tekanan udara menurun dapat menandai système cuaca aktif.",
  "Séisme Tectonique": "Contoh: gempa tektonik kuat dapat memicu tsunami jika pusatnya berada di laut.",
  "Magnitude": "Contoh: magnitudo 5 tidak selalu berarti dampaknya sama di semua tempat.",
  "Épicentre": "Contoh: episenter gempa berada 80 km barat daya kota.",
  "Hypocentre": "Contoh: hiposenter dangkal sering terasa lebih kuat di permukaan.",
  "Tsunami": "Contoh: peringatan dini tsunami harus diikuti dengan evakuasi cepat.",
  "Prévision Saisonnière": "Contoh: prakiraan musim membantu petani menentukan waktu tanam.",
  "El Niño": "Contoh: El Niño kuat sering berkaitan dengan kemarau lebih kering.",
  "La Niña": "Contoh: La Niña bisa membuat musim hujan lebih basah.",
  "Oscillation de Madden-Julian": "Contoh: fase MJO aktif sering memperkuat hujan di wilayah Indonesia.",
  "Indice UV": "Contoh: indeks UV ekstrem memerlukan topi, tabir surya, dan pembatasan aktivitas luar ruang.",
  "Visibilité": "Contoh: kabut tebal menurunkan jarak pandang di bandara.",
  "Vortex Tornade/Like Waterspout": "Contoh: awan gelap menjulang bisa mendahului puting beliung.",
  "Météo Extrême": "Contoh: notifikasi cuaca ekstreme dikirim untuk mengurangi risiko warga.",
  "Éclair": "Contoh: hindari lapangan terbuka saat petir sering terjadi.",
  "Image Astronomique du Jour": "Contoh: APOD hari ini menampilkan nebula yang dipotret teleskop luar angkasa.",
  "Near-Earth Object": "Exemple : le système NeoWs surveille de nombreux NEO chaque jour.",
  "Near Earth Object Web Service": "Exemple : le cron des comètes utilise NeoWs de manière limitée à partir d'un serveur.",
  "Aphelion": "Exemple : les comètes se déplacent plus lentement lorsqu'elles approchent de l'aphélie.",
  "Perihelion": "Exemple : les comètes sont souvent plus actives lorsqu'elles approchent du périlhélie.",
  "Asteroid": "Exemple : les gros astéroïdes peuvent avoir une forme non régulière.",
  "Comet": "Exemple : la queue des comètes est toujours poussée loin du Soleil par le vent solaire.",
  "Meteor": "Exemple : les gens aiment souvent appeler les météores des étoiles filantes.",
  "Meteorite": "Exemple : les météorites de fer sont généralement plus lourdes que les roches ordinaires.",
  "Meteoroid": "Exemple : les météoroides peuvent provenir de fragments d'astéroïdes ou de comètes.",
  "Rover": "Exemple : Perseverance est un rover de la NASA sur Mars.",
  "Martian Sol": "Exemple : les photos de rover sont souvent étiquetées en fonction du sol de prise de vue.",
  "Spectrometer": "Exemple : le spectromètre aide à identifier les minéraux dans les roches de Mars.",
  "Regolith": "Exemple : les traces de rover sont claires sur la regolith de Mars.",
  "Eclipse": "Exemple : l'éclipse solaire se produit lorsque la Lune est entre la Terre et le Soleil.",
  "Aurora": "Exemple : les fortes tempêtes géomagnétiques peuvent étendre la zone d'aurora.",
  "Solar Flare": "Exemple : les éruptions solaires de classe X sont considérées comme fortes.",
  "Coronal Mass Ejection": "Exemple : les CME qui se dirigent vers la Terre peuvent déclencher des tempêtes géomagnétiques.",
  "Light-Year": "Exemple : la plus proche étoile après le Soleil est à plus de quatre années-lumière de distance.",
  "Nebula": "Exemple : la nébuleuse d'Orion peut être vue avec un petit télescope.",
  "Exoplanet": "Exemple : les télescopes spatiaux cherchent des exoplanètes en utilisant la méthode de transit.",
  "Planetary Transit": "Exemple : le transit est utilisé pour trouver de nombreux exoplanètes.",
  "Escape Velocity": "Exemple : les fusées doivent dépasser la vitesse de libération pour quitter la Terre.",
  "Microgravity": "Exemple : les astronautes effectuent des expériences en microgravité à bord de la Station spatiale internationale."
};

const glossaryTermsRu: Record<string, string> = {
  "Light Rain": "Лёгкий дождь",
  "Moderate Rain": "Умеренный дождь",
  "Heavy Rain": "Сильный дождь",
  "Drizzle": "Морось",
  "Cumulonimbus Cloud": "Кумулонimbus",
  "Strong Wind": "Сильный ветер",
  "High Wave": "Высокая волна",
  "Maximum Temperature": "Максимальная температура",
  "Humidity": "Влажность",
  "Air Pressure": "Давление воздуха",
  "Tectonic Earthquake": "Тектоническое землетрясение",
  "Magnitude": "Магнитуда",
  "Epicenter": "Эпицентр",
  "Hypocenter": "Гипоцентр",
  "Tsunami": "Цунами",
  "Seasonal Forecast": "Сезонное прогнозирование",
  "El Nino": "Эль-Нино",
  "La Nina": "Ла-Нина",
  "Madden-Julian Oscillation": "Осцилляция Маддена-Юлиана",
  "UV Index": "Индекс УФ-излучения",
  "Visibility": "Видимость",
  "Waterspout/Tornado-like Vortex": "Водяной смерч/тornado-подобный вихрь",
  "Extreme Weather": "Экстремальное метеорологическое явление",
  "Lightning": "Молния",
  "Astronomy Picture of the Day": "Астрономическая фотография дня",
  "Near-Earth Object": "Близкое к Земле небесное тело",
  "Near Earth Object Web Service": "Веб-сервис близких к Земле небесных тел",
  "Aphelion": "Афелий",
  "Perihelion": "Перигелий",
  "Asteroid": "Астероид",
  "Comet": "Комета",
  "Meteor": "Метеор",
  "Meteorite": "Метеорит",
  "Meteoroid": "Метеороид",
  "Rover": "Ровер",
  "Martian Sol": "Марсианский день",
  "Spectrometer": "Спектрометр",
  "Regolith": "Реголит",
  "Eclipse": "Затмение",
  "Aurora": "Аурора",
  "Solar Flare": "Солнечный взрыв",
  "Coronal Mass Ejection": "Выброс массы короны",
  "Light-Year": "Лига светимости",
  "Nebula": "Небула",
  "Exoplanet": "Экзопланета",
  "Planetary Transit": "Планетарный переход",
  "Escape Velocity": "Величина бегства",
  "Microgravity": "Микрогравитация"
};

const glossaryTermsFr: Record<string, string> = {
  "Light Rain": "Pluie légère",
  "Moderate Rain": "Pluie modérée",
  "Heavy Rain": "Pluie forte",
  "Drizzle": "Bruine",
  "Cumulonimbus Cloud": "Nuage cumulonimbus",
  "Strong Wind": "Vent fort",
  "High Wave": "Houle élevée",
  "Maximum Temperature": "Température maximale",
  "Humidity": "Humidité",
  "Air Pressure": "Pression atmosphérique",
  "Tectonic Earthquake": "Séisme tectonique",
  "Magnitude": "Magnitude",
  "Epicenter": "Épicentre",
  "Hypocenter": "Hypocentre",
  "Tsunami": "Tsunami",
  "Seasonal Forecast": "Prévision saisonnière",
  "El Nino": "El Niño",
  "La Nina": "La Niña",
  "Madden-Julian Oscillation": "Oscillation de Madden-Julian",
  "UV Index": "Indice UV",
  "Visibility": "Visibilité",
  "Waterspout/Tornado-like Vortex": "Tourbillon aquatique/équivalent tornade",
  "Extreme Weather": "Météo extrême",
  "Lightning": "Éclair",
  "Astronomy Picture of the Day": "Image astronomique du jour",
  "Near-Earth Object": "Objet proche de la Terre",
  "Near Earth Object Web Service": "Service web objet proche de la Terre",
  "Aphelion": "Aphélie",
  "Perihelion": "Périhélie",
  "Asteroid": "Astromètre",
  "Comet": "Comète",
  "Meteor": "Météore",
  "Meteorite": "Météorite",
  "Meteoroid": "Météoroïde",
  "Rover": "Rover",
  "Martian Sol": "Sol martien",
  "Spectrometer": "Spectromètre",
  "Regolith": "Régolith",
  "Eclipse": "Éclipse",
  "Aurora": "Aurore",
  "Solar Flare": "Éruption solaire",
  "Coronal Mass Ejection": "Éjection de masse coronale",
  "Light-Year": "Anneau lumineux",
  "Nebula": "Nébuleuse",
  "Exoplanet": "Exoplanète",
  "Planetary Transit": "Traversée planétaire",
  "Escape Velocity": "Vitesse d'échappement",
  "Microgravity": "Microgravité"
};

function toDefinition(language: SiteLanguage, text: string) {
  if (language === 'id') return text;
  if (language === 'ms') return text.replaceAll('yang', 'yang').replaceAll('Bumi', 'Bumi');
  if (language === 'zh') return `Istilah sains ini merujuk pada: ${text}`;
  if (language === 'ja') return `この科学用語は次を指します: ${text}`;
  return text;
}

function mapRows(rows: string[][], category: GlossaryCategory, source: string): GlossaryTerm[] {
  return rows.map((row) => ({
    id: `${category.toLowerCase()}-${row[0]}`,
    category,
    term: {
      id: row[1],
      en: row[2],
      ms: row[3],
      zh: row[4],
      ja: row[5],
      ru: glossaryTermsRu[row[2]] || row[2],
      fr: glossaryTermsFr[row[2]] || row[2],
    },
    definition: {
      id: row[6],
      en: toDefinition('en', row[6]),
      ms: toDefinition('ms', row[6]),
      zh: toDefinition('zh', row[6]),
      ja: toDefinition('ja', row[6]),
      ru: glossaryDefsRu[row[2]] || row[6],
      fr: glossaryDefsFr[row[2]] || row[6],
    },
    example: {
      id: row[7],
      en: row[7].replace('Contoh:', 'Example:'),
      ms: row[7].replace('Contoh:', 'Contoh:'),
      zh: row[7].replace('Contoh:', '示例:'),
      ja: row[7].replace('Contoh:', '例:'),
      ru: glossaryExsRu[row[2]] || row[7],
      fr: glossaryExsFr[row[2]] || row[7],
    },
    image: `https://image.pollinations.ai/prompt/${encodeURIComponent(`${category} science glossary illustration ${row[2]} meteorology astronomy educational poster realistic`)}?width=1000&height=620&nologo=true&seed=${encodeURIComponent(`${category}-${row[0]}`)}`,
    source,
    updatedAt,
  }));
}

export const glossarySeed: GlossaryTerm[] = [
  ...mapRows(bmkgTerms, 'BMKG', 'BMKG public weather, climate, earthquake terminology'),
  ...mapRows(nasaTerms, 'NASA', 'NASA public astronomy and spaceflight terminology'),
];

export function getGlossarySeed() {
  return glossarySeed;
}
