import { landingTextRu } from './translations/landingRu';
import { landingTextFr } from './translations/landingFr';
import type { SiteLanguage } from './i18n';

const landingTextBase = {
  id: {
    loading: 'Loading...',
    readMore: 'Baca Selengkapnya',
    readDetail: 'Lihat Detail',
    previous: 'Sebelumnya',
    next: 'Selanjutnya',
    page: 'Halaman',
    all: 'Semua',
    total: 'Total',
    article: 'Artikel',
    statsMeteorites: 'Meteorit Terdata Dunia',
    statsCollectors: 'Kolektor Indonesia',
    statsAsteroids: 'Asteroid Dekat Bumi Hari Ini',
    statsAstronauts: 'Astronot di Orbit Saat Ini',
    objectUnit: 'Objek',
    crewUnit: 'Kru',
    dailyUpdate: 'Pembaruan Harian',
    skyObjectToday: 'Benda Langit Hari Ini',
    nasaDailyData: 'Data langsung dari NASA - diperbarui setiap hari',
    latestEarthPhoto: 'Memuat foto Bumi terbaru...',
    epicUnavailable: 'Foto Bumi EPIC tidak tersedia saat ini',
    epicMonitor: 'Monitor Satelit EPIC',
    epicDescription: 'Foto Bumi terbaru yang diambil oleh kamera EPIC milik NASA dari jarak 1,5 juta km, memperlihatkan sisi Bumi yang terkena cahaya matahari.',
    latitude: 'Lintang',
    longitude: 'Bujur',
    latest: 'Terbaru',
    monitorEpic: 'Pantau EPIC',
    viewAllMeteorCatalog: 'Lihat Semua Katalog Meteorit',
    blogLatest: 'Artikel Astronomi Terbaru',
    newsletterTitle: 'Langganan Berita',
    newsletterDescription: 'Masukkan alamat email Anda untuk menerima notifikasi gratis saat terjadi kejatuhan meteor baru serta artikel astronomi langsung di kotak masuk Anda.',
    newsletterSuccess: 'Terima kasih! Anda telah terdaftar dalam newsletter kami.',
    emailPlaceholder: 'Masukkan alamat email Anda',
    subscribeNow: 'Berlangganan Sekarang',
    blogTitle: 'Blog Astronomi & Meteorit',
    blogDescription: 'Berita sains terbaru, panduan mengidentifikasi batuan langit, dan trivia astronomi menarik.',
    searchScience: 'Cari artikel sains...',
    noArticles: 'Belum ada artikel',
    noGeneratedArticles: 'Artikel AI belum digenerate. Pergi ke Admin - Manajemen Artikel - klik "Buat Artikel AI".',
    noSearchMatch: 'Tidak ada artikel yang cocok dengan pencarian Anda.',
    cometBadge: 'Edukasi & Kabar Batuan Luar Angkasa',
    cometTitle: 'Artikel Komet & Asteroid',
    cometDescription: 'Analisis sains populer, hasil pelacakan objek melintas dekat Bumi (NeoWs NASA), dan artikel edukasi asteroid real-time.',
    searchComet: 'Cari artikel komet & asteroid...',
    noCometArticles: 'Belum ada artikel komet & asteroid',
    noCometGenerated: 'Gunakan menu Admin untuk memicu rilis otomatis artikel komet.',
    redPlanet: 'Planet Merah',
    marsLatest: 'Artikel Mars Terbaru',
    marsDescription: 'Kabar rover, geologi, cuaca ekstrem, dan masa depan manusia di Mars dari arsip artikel Meteorit Indonesia.',
    viewAllMars: 'Lihat Semua Artikel Mars',
    readMars: 'Baca Artikel Mars',
    communityTitle: 'Meteor atau Bukan?',
    communityP1: 'Apakah Anda menemukan batu unik yang tidak biasa di alam dan ragu apakah itu batuan bumi biasa atau meteorit luar angkasa?',
    communityP2: 'Unggah foto batu temuan Anda ke forum diskusi kami dan mintalah penilaian dari para ahli astronomi serta anggota komunitas kami melalui sistem voting interaktif.',
    askForum: 'Tanyakan di Forum Diskusi',
    welcome: 'Selamat Datang',
    forumVisit: 'Kunjungi forum diskusi untuk menulis pertanyaan Anda',
    googleLoginPrompt: 'Masuk menggunakan Akun Google untuk berpartisipasi',
    googleLogin: 'Masuk dengan Google',
    donationTitle: 'Dukung Eksplorasi Sains & Komunitas',
    donationDescription: 'Meteorit Indonesia adalah platform nirlaba yang didukung oleh komunitas. Donasi Anda membantu membiayai operasional hosting, API NASA, dan pengembangan riset edukasi luar angkasa.',
    donationStepEmail: 'Langkah 1: Masukkan Alamat Email',
    donationStepAmount: 'Langkah 2: Pilih Jumlah Donasi',
    donationCustom: 'Masukkan jumlah donasi khusus',
    donationButton: 'Kirim Donasi via Midtrans',
    donationProcessing: 'Memproses Pembayaran...',
    liveSpaceData: 'Live Data Antariksa',
    missionControlTitle: 'Space Mission Control',
    missionControlDesc: 'Data real-time misi orbit Bumi dan stasiun ruang angkasa',
    
    // New Translations
    nasaApodLabel: '📡 NASA APOD',
    nasaEpicLabel: '🌍 NASA EPIC',
    apodTitle: 'Astronomy Picture of the Day',
    epicTitle: 'Earth Polychromatic Imaging Camera',
    upcomingLaunch: 'Peluncuran Terdekat',
    scientificMission: 'Misi Sains',
    goForLaunch: 'Terjadwal / Siap Meluncur',
    countdownDays: 'Hari',
    countdownHours: 'Jam',
    countdownMinutes: 'Mnt',
    countdownSeconds: 'Det',
    countingDown: 'Menghitung mundur peluncuran...',
    launchDataSource: 'Sumber data: Launch Library API →',
    issTrackerTitle: 'Live ISS Tracker',
    issActive: 'Aktif',
    issMapUnavailable: 'Peta tidak tersedia',
    issUpdateInterval: 'Diperbarui otomatis setiap 5 detik',
    activeAstronauts: 'Kru di Orbit Saat Ini',
    astronautSub: 'astronot, kosmonot, dan taikonaut aktif',
    viewAllAstronauts: '👨‍🚀 Lihat Semua Profil Astronot →',
    astronautDataSource: 'Sumber data: Dataset internal & Open Notify →',
    donationEmailAlert: 'Silakan masukkan email Anda terlebih dahulu untuk tanda bukti donasi.',
    donationSuccessAlert: 'Donasi berhasil! Terima kasih atas dukungan Anda.',
    donationPendingAlert: 'Pembayaran tertunda, silakan selesaikan pembayaran Anda.',
    donationFailAlert: 'Pembayaran donasi gagal.',
    donationStartFailAlert: 'Gagal memulai pembayaran donasi. Silakan coba kembali.',
    dataAttribution: '🛰️ Atribusi Data:',
    dataProvidedBy: 'Data di situs ini disediakan oleh',
    freeToUse: 'bebas digunakan sesuai',
    nasaPolicy: 'kebijakan NASA',
    photoCopyrightNote: 'Hak cipta foto APOD tercantum pada masing-masing gambar sesuai ketentuan NASA.',
    glossaryTitle: 'Glossarium Sains Multi Bahasa',
    glossaryDescription: 'Kamus istilah meteorologi, geofisika, astronomi, dan misi antariksa untuk membantu pembaca memahami kata-kata teknis seperti hujan ringan, kosame, NEO, APOD, sol Mars, dan cuaca antariksa.',
    glossaryBadge: 'BMKG + NASA',
    openGlossary: 'Buka Glossarium',
    backToGlossary: '← Kembali ke Glossarium',
    definitionLabel: 'Definisi',
    exampleLabel: 'Contoh',
    richDiscussion: 'Pembahasan Ilmiah',
    translationsLabel: 'Terjemahan',
    updatedAtLabel: 'Diperbarui:',
    sourceLabel: 'Sumber:',
    glossaryError: 'Istilah tidak ditemukan.',
    // FireballEonetSection
    earthMonitorBadge: '🌍 Pemantauan Bumi dari Antariksa',
    earthMonitorTitle: 'Peristiwa Alam & Bola Api',
    earthMonitorDesc: 'Data real-time dari NASA JPL Fireball API dan NASA EONET Earth Observatory — pemantauan bumi langsung dari luar angkasa.',
    fireballTab: '🔥 Fireball',
    eonetTab: '🌍 Peristiwa Alam',
    liveFireballFeed: 'Live JPL Fireball Feed',
    noFireballData: 'Tidak ada data fireball terbaru.',
    viewAllMonitoring: 'Lihat semua di Monitoring →',
    noFireballArticles: 'Belum ada artikel Fireball.',
    noEonetArticles: 'Belum ada artikel Peristiwa Alam.',
    autoCronFill: 'Cron otomatis akan mengisi artikel setiap hari.',
    viewAllFireball: 'Lihat Semua Artikel Fireball →',
    viewAllEonet: 'Lihat Semua Artikel Peristiwa Alam →',
    // List page UI
    totalArticles: 'Total: {n} Artikel',
    searchFireball: 'Cari artikel bola api & fireball...',
    searchEonet: 'Cari artikel peristiwa alam...',
    searchApod: 'Cari foto antariksa, tanggal, atau topik...',
    apodGalleryBadge: 'NASA Astronomy Picture of the Day (APOD)',
    apodGalleryTitle: 'Galeri Foto Antariksa',
    apodGalleryDesc: 'Jelajahi keindahan semesta raya melalui kurasi gambar astronomi harian resmi dari NASA, lengkap dengan penjelasan ilmiah yang diterjemahkan menggunakan AI.',
    apodShowingOf: 'Menampilkan {filtered} dari {total} arsip foto.',
    apodNoResults: 'Tidak ada foto antariksa yang cocok dengan pencarian Anda.',
    viewDetail: 'Lihat Detail →',
    readMore2: 'Baca Selengkapnya →',
    fireballListBadge: '🔥 Data Real-Time NASA/JPL Fireball Data API',
    fireballListTitle: 'Laporan Bola Api (Fireball)',
    fireballListDesc: 'Analisis sains populer tentang peristiwa fireball — bola api meteor yang terdeteksi memasuki atmosfer Bumi berdasarkan data sensor inframerah global NASA/JPL.',
    noFireballArticlesList: 'Belum ada artikel Fireball',
    noFireballCron: 'Gunakan menu Admin untuk memicu rilis otomatis artikel Fireball.',
    noFireballMatch: 'Tidak ada artikel yang cocok dengan pencarian Anda.',
    kometListBadge: '☄️ Edukasi & Kabar Batuan Luar Angkasa',
    kometListTitle: 'Artikel Komet & Asteroid',
    kometListDesc: 'Analisis sains populer, hasil pelacakan objek melintas dekat Bumi (NeoWs NASA), dan artikel edukasi asteroid real-time.',
    noKometArticlesList: 'Belum ada artikel komet & asteroid',
    noKometCron: 'Gunakan menu Admin untuk memicu rilis otomatis artikel komet.',
    noKometMatch: 'Tidak ada artikel yang cocok dengan pencarian Anda.',
    eonetListBadge: '🌍 Data Real-Time NASA EONET v3 Earth Observatory',
    eonetListTitle: 'Peristiwa Alam Aktif',
    eonetListDesc: 'Pantau peristiwa alam yang sedang aktif di Bumi — gunung berapi, kebakaran hutan, badai dahsyat, dan fenomena alam lainnya yang dipantau NASA dari luar angkasa.',
    noEonetArticlesList: 'Belum ada artikel Peristiwa Alam',
    noEonetCron: 'Gunakan menu Admin untuk memicu rilis otomatis artikel EONET.',
    noEonetMatch: 'Tidak ada artikel yang cocok dengan pencarian Anda.',
    blogListTitle: 'Blog Astronomi & Meteorit',
    blogListDesc: 'Berita sains terbaru, panduan mengidentifikasi batuan langit, dan trivia astronomi menarik.',
    // ArticleActions
    ttsPlay: '🔊 Putar Suara AI',
    ttsStop: '⏹️ Hentikan Suara',
    downloadPdf: '📥 Download PDF',
    downloadShareCard: '📸 Download Share Card',
    shareLabel: 'BAGIKAN:',
    copyLink: '🔗 Salin',
    linkCopied: 'Tautan artikel berhasil disalin!',
    // Article back nav
    backToBlog: '← Kembali ke Daftar Artikel',
    backToFireball: '← Kembali ke Fireball',
    backToEonet: '← Kembali ke Peristiwa Alam',
    backToKomet: '← Kembali ke Artikel Komet',
    backToMars: '← Kembali ke Artikel Mars',
    backToApod: '← Kembali ke Galeri APOD',
    releaseDate: 'Tanggal Rilis',
    copyrightLabel: 'Hak Cipta / Sumber',
    scientificExplanation: 'Penjelasan Ilmiah',
    originalExplanation: 'Original English Explanation',
    apodError: 'Foto antariksa tidak ditemukan atau format tanggal salah.',
    backToAstronaut: '← Kembali ke Profil Astronot',
    astroError: 'Profil astronot tidak ditemukan.',
    astroStatusActive: 'Sedang Bertugas',
    astroStatusUpcoming: 'Misi Mendatang',
    astroStatusReturned: 'Sudah Kembali',
    astroCountry: 'Asal Negara',
    astroAgency: 'Agensi',
    astroMissionDuration: 'Durasi Misi',
    astroUpcomingText: 'Terjadwal',
    daysUnit: 'Hari',
    astroBioTitle: 'Biografi & Misi',
    meteorError: 'Data meteorit tidak ditemukan.',
    backToCatalog: 'Kembali ke Katalog',
    backToEncyclopedia: '← Kembali ke Katalog Ensiklopedia',
    physicalSpec: 'Spesifikasi Fisik',
    rockName: 'Nama Batuan:',
    rockType: 'Tipe / Kelas:',
    estimatedMass: 'Estimasi Massa:',
    foundYear: 'Tahun Ditemukan:',
    latitudeLabel: 'Koordinat Lintang:',
    longitudeLabel: 'Koordinat Bujur:',
    descriptionHistory: 'Deskripsi & Analisis Sejarah',
    landingLocation: 'Lokasi Geografis Pendaratan',
    impactCoordinates: 'Koordinat Jatuh:',
    openInGoogleMaps: 'Buka di Google Maps →',
    articleNotFound: 'Artikel tidak ditemukan.',
    visitWebsite: 'Kunjungi Situs Kami',
    // Star Map / Langit Malam
    starMapBadge: '🌠 Peta Bintang Interaktif',
    starMapTitle: 'Langit Malam',
    starMapSubtitle: 'Izinkan akses lokasi GPS atau pilih kota Anda untuk menggeser peta koordinat rasi bintang malam ini secara dinamis.',
    gpsDetecting: 'Mendeteksi Lokasi...',
    gpsDetected: 'GPS Terdeteksi:',
    useGpsBtn: '📍 Gunakan Lokasi GPS Saya',
    gpsNotSupported: 'Browser Anda tidak mendukung GPS.',
    gpsErrorDenied: 'Akses GPS ditolak atau tidak tersedia. Pilih kota secara manual.',
    orSelectCity: 'ATAU PILIH KOTA',
    orManualInput: 'ATAU INPUT MANUAL',
    latLabel: 'Latitude (Lintang)',
    lonLabel: 'Longitude (Bujur)',
    latPlaceholder: 'Contoh: -6.2088',
    lonPlaceholder: 'Contoh: 106.8456',
    latError: 'Latitude harus berupa angka antara -90 dan 90.',
    lonError: 'Longitude harus berupa angka antara -180 dan 180.',
    applyCoordsBtn: 'Terapkan Koordinat Kustom',
    nightSkyAt: 'Langit Malam di',
    openFullScreen: 'Buka Layar Penuh ↗',
    starMapProvidedBy: 'Peta bintang disajikan oleh',
    starMapInstructions: '🖱️ Klik & seret untuk memutar langit • Scroll untuk zoom',
    constellationTitle: 'Konstelasi Malam Ini',
    constellationDesc: 'Identifikasi rasi bintang yang terlihat dari kota Anda malam ini berdasarkan posisi dan waktu real-time.',
    moonPhaseTitle: 'Fase Bulan',
    moonPhaseDesc: 'Pantau fase bulan hari ini dan prediksi fase berikutnya untuk perencanaan observasi astronomi terbaik.',
    visiblePlanetsTitle: 'Planet yang Terlihat',
    visiblePlanetsDesc: 'Ketahui planet mana yang bisa diamati dengan mata telanjang atau teleskop dari lokasi Anda malam ini.',
    earthMonitorWidget: 'Live Data Bumi untuk Komunitas Langit Malam',
    earthMonitorSubtitle: 'Earth Monitoring Simulator',
    tabQuake: '🌋 Gempa Terkini',
    tabWeather: '🌧️ Cuaca & Hujan',
    tabEnergy: '☀️ Angin & Surya',
    quakePanelSub: 'Live JSON BMKG TEWS',
    quakePanelTitle: 'Gempa Bumi Terkini',
    quakeRefreshTitle: 'Muat ulang data BMKG',
    quakeMagnitude: 'Magnitudo',
    quakeDepth: 'Kedalaman',
    quakeRegion: 'Wilayah',
    quakeTsunami: 'Potensi Tsunami',
    quakeLoadingRegion: 'Memuat data wilayah...',
    quakeUpdate: 'Update:',
    quakeIndependent: 'Fetch independen dari BMKG.',
    weatherSub: 'Data cuaca real-time',
    weatherTitle: 'Info Cuaca & Kondisi Langit',
    weatherGpsDetecting: 'Mendeteksi lokasi Anda secara otomatis via GPS/Wi-Fi...',
    weatherGpsFound: 'Lokasi terdeteksi:',
    weatherGpsDenied: 'Izin lokasi ditolak. Gunakan form pencarian manual di bawah.',
    weatherGpsError: 'Gagal memuat data lokasi otomatis. Coba cari lokasi secara manual.',
    weatherOwLoading: 'Mengambil data cuaca aktual dari OpenWeather...',
    weatherOwActual: '🌤️ OpenWeather — Data Aktual',
    weatherOwError: 'OpenWeather tidak tersedia.',
    weatherOwCacheNote: 'Sumber: OpenWeather API · Cache 15 menit',
    weatherSearchLabel: 'Cari alamat, kawasan, desa, kota, atau koordinat',
    weatherSearchPlaceholder: 'Jababeka, Jl Sudirman Jakarta, Desa Cibatu, -6.2088, 106.8456',
    weatherSearchBtn: 'Cari',
    weatherSearchHint: 'Bisa pakai nama kawasan, jalan, desa/kelurahan, kecamatan, kota/kabupaten, atau titik koordinat latitude, longitude.',
    weatherSearchMin: 'Masukkan minimal 3 karakter lokasi atau koordinat lengkap.',
    weatherSearchSuccess: 'Data realtime untuk {label} berhasil dimuat.',
    weatherSearchFail: 'Gagal mencari lokasi.',
    weatherSimResult: 'Hasil pencarian — Simulator BMKG',
    weatherTemp: 'Suhu',
    weatherRain: 'Hujan',
    weatherHumidity: 'Kelembapan',
    weatherCondition: 'Kondisi',
    weatherRainChance: 'peluang hujan',
    weatherPrecipitation: 'presipitasi',
    weatherFeelsLike: 'Terasa',
    weatherHumidityLabel: 'Kelembapan',
    weatherWind: 'Angin',
    weatherClouds: 'Awan',
    weatherHumidityHigh: 'Lembap',
    weatherHumidityNormal: 'Normal',
    weatherHumidityLow: 'Kering',
    weatherCloudsLow: 'Cerah',
    weatherCloudsMid: 'Berawan',
    weatherCloudsHigh: 'Mendung',
    weatherTempCold: 'Dingin/Sejuk',
    weatherTempNormal: 'Normal',
    weatherTempHot: 'Panas',
    weatherRainLow: 'Rendah',
    weatherRainMid: 'Sedang',
    weatherRainHigh: 'Tinggi',
    weatherIntensity: 'Intensitas hujan',
    weatherCityTonight: 'Suhu Udara {city} Malam Ini:',
    energySub: 'Simulator potensi RE-Atlas',
    energyTitle: 'Energi Angin & Surya',
    energyGpsFound: 'Lokasi terdeteksi otomatis:',
    energyGpsDenied: 'Izin lokasi ditolak. Gunakan form pencarian manual di bawah.',
    energyGpsError: 'Gagal memuat data lokasi otomatis. Coba cari lokasi secara manual.',
    energyRealtimeResult: 'Hasil pencarian realtime',
    energyWind10m: 'Angin 10m',
    energyWindDir: 'Arah Angin',
    energySolar: 'Radiasi Surya',
    energySolarNote: 'Data ini adalah pembacaan cuaca permukaan realtime dari Open-Meteo, cocok untuk indikasi awal kondisi angin dan matahari setempat.',
    energySolarLabel: 'Surya',
    energyWindLabel: 'Angin',
    energyTopSolar: 'Radiasi Matahari:',
    earthDataSource: 'Data live disediakan oleh BMKG, Open-Meteo, dan ESDM RE-Atlas. Widget ini berjalan independen dari NASA_API_KEY.',
    pushTitle: 'Notifikasi Antariksa Live',
    pushDesc: 'Aktifkan notifikasi browser untuk info live asteroid dekat Bumi, gempa BMKG, dan galeri APOD NASA.',
    pushDismiss: 'Nanti Saja',
    pushAccept: 'Aktifkan',
    pushLoading: 'Mengaktifkan...',
    astroLiveArchive: 'Live & arsip misi',
    astroPageTitle: 'Database Manusia di Antariksa',
    astroPageDesc1: 'Halaman ini merangkum profil astronot, kosmonot, dan taikonaut dalam tiga kelompok.',
    astroPageDesc2: 'Kru aktif biasanya tinggal di ISS atau Tiangong selama berbulan-bulan untuk menjalankan eksperimen mikrogravitasi.',
    astroTotalProfiles: 'Total Profil',
    astroActive: 'Aktif',
    astroUpcomingStat: 'Mendatang',
    astroAlumni: 'Alumni',
    astroTabActive: 'Sedang di Antariksa',
    astroTabActiveTitle: 'Kru yang Sedang Bertugas',
    astroTabActiveDesc: 'Astronot, kosmonot, dan taikonaut yang sedang menjalankan misi di orbit Bumi.',
    astroTabUpcoming: 'Misi Mendatang',
    astroTabUpcomingTitle: 'Kru yang Akan Meluncur',
    astroTabUpcomingDesc: 'Nama-nama kru yang sudah masuk jadwal misi berikutnya menuju stasiun antariksa atau program eksplorasi.',
    astroTabReturned: 'Pahlawan Antariksa',
    astroTabReturnedTitle: 'Alumni dan Kru yang Sudah Kembali',
    astroTabReturnedDesc: 'Arsip kru yang pernah bertugas di ISS, Tiangong, atau misi orbit lain dan sudah kembali ke Bumi.',
    astroNoData: 'Belum ada data untuk kategori ini.',
    readFullBio: 'Lihat Biografi Lengkap',
    updatedAt: 'Diperbarui',
    missionLabel: 'Misi',
  },
  en: {
    loading: 'Loading...',
    readMore: 'Read More',
    readDetail: 'View Details',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    all: 'All',
    total: 'Total',
    article: 'Articles',
    statsMeteorites: 'Documented Meteorites Worldwide',
    statsCollectors: 'Indonesian Collectors',
    statsAsteroids: 'Near-Earth Asteroids Today',
    statsAstronauts: 'Astronauts in Orbit Now',
    objectUnit: 'Objects',
    crewUnit: 'Crew',
    dailyUpdate: 'Daily Update',
    skyObjectToday: 'Sky Object Today',
    nasaDailyData: 'Live NASA data - updated daily',
    latestEarthPhoto: 'Loading the latest Earth photo...',
    epicUnavailable: 'EPIC Earth photo is unavailable right now',
    epicMonitor: 'EPIC Satellite Monitor',
    epicDescription: 'The latest Earth photo captured by NASA EPIC from 1.5 million km away, showing the sunlit side of Earth.',
    latitude: 'Latitude',
    longitude: 'Longitude',
    latest: 'Latest',
    monitorEpic: 'Monitor EPIC',
    viewAllMeteorCatalog: 'View All Meteorite Catalogs',
    blogLatest: 'Latest Astronomy Articles',
    newsletterTitle: 'Subscribe to News',
    newsletterDescription: 'Enter your email to receive free notifications about new meteor falls and astronomy articles directly in your inbox.',
    newsletterSuccess: 'Thank you! You are now subscribed to our newsletter.',
    emailPlaceholder: 'Enter your email address',
    subscribeNow: 'Subscribe Now',
    blogTitle: 'Astronomy & Meteorite Blog',
    blogDescription: 'Latest science news, guides to identifying sky rocks, and interesting astronomy trivia.',
    searchScience: 'Search science articles...',
    noArticles: 'No articles yet',
    noGeneratedArticles: 'AI articles have not been generated yet. Open Admin - Article Management - click "Create AI Article".',
    noSearchMatch: 'No articles match your search.',
    cometBadge: 'Education & Space Rock News',
    cometTitle: 'Comet & Asteroid Articles',
    cometDescription: 'Popular science analysis, NASA NeoWs near-Earth tracking, and real-time asteroid education articles.',
    searchComet: 'Search comet & asteroid articles...',
    noCometArticles: 'No comet & asteroid articles yet',
    noCometGenerated: 'Use the Admin menu to trigger automatic comet article publishing.',
    redPlanet: 'Red Planet',
    marsLatest: 'Latest Mars Articles',
    marsDescription: 'Rover news, geology, extreme weather, and the future of humans on Mars from Meteorit Indonesia articles.',
    viewAllMars: 'View All Mars Articles',
    readMars: 'Read Mars Article',
    communityTitle: 'Meteor or Not?',
    communityP1: 'Did you find an unusual stone outdoors and wonder whether it is ordinary Earth rock or a space meteorite?',
    communityP2: 'Upload photos of your find to our forum and ask astronomers and community members for interactive voting-based review.',
    askForum: 'Ask in the Forum',
    welcome: 'Welcome',
    forumVisit: 'Visit the discussion forum to write your question',
    googleLoginPrompt: 'Sign in with Google to participate',
    googleLogin: 'Sign in with Google',
    donationTitle: 'Support Science Exploration & Community',
    donationDescription: 'Meteorit Indonesia is a community-supported nonprofit platform. Your donation helps fund hosting, NASA APIs, and space education research.',
    donationStepEmail: 'Step 1: Enter Email Address',
    donationStepAmount: 'Step 2: Choose Donation Amount',
    donationCustom: 'Enter a custom donation amount',
    donationButton: 'Send Donation via Midtrans',
    donationProcessing: 'Processing Payment...',
    liveSpaceData: 'Live Space Data',
    missionControlTitle: 'Space Mission Control',
    missionControlDesc: 'Real-time Earth orbit mission and space station data',
    
    // New Translations
    nasaApodLabel: '📡 NASA APOD',
    nasaEpicLabel: '🌍 NASA EPIC',
    apodTitle: 'Astronomy Picture of the Day',
    epicTitle: 'Earth Polychromatic Imaging Camera',
    upcomingLaunch: 'Upcoming Launch',
    scientificMission: 'Scientific Mission',
    goForLaunch: 'Go for Launch',
    countdownDays: 'Days',
    countdownHours: 'Hrs',
    countdownMinutes: 'Mins',
    countdownSeconds: 'Secs',
    countingDown: 'Counting down to launch...',
    launchDataSource: 'Data source: Launch Library API →',
    issTrackerTitle: 'Live ISS Tracker',
    issActive: 'Active',
    issMapUnavailable: 'Map unavailable',
    issUpdateInterval: 'Updated automatically every 5 seconds',
    activeAstronauts: 'Crews in Orbit Now',
    astronautSub: 'active astronauts, cosmonauts, and taikonauts',
    viewAllAstronauts: '👨‍🚀 View All Astronaut Profiles →',
    astronautDataSource: 'Data source: Internal Dataset & Open Notify →',
    donationEmailAlert: 'Please enter your email address first for donation receipt.',
    donationSuccessAlert: 'Donation successful! Thank you for your support.',
    donationPendingAlert: 'Payment pending, please complete your payment.',
    donationFailAlert: 'Donation payment failed.',
    donationStartFailAlert: 'Failed to initiate donation payment. Please try again.',
    dataAttribution: '🛰️ Data Attribution:',
    dataProvidedBy: 'Data on this site is provided by',
    freeToUse: 'free to use according to',
    nasaPolicy: 'NASA policies',
    photoCopyrightNote: 'APOD photo copyrights are credited to their respective owners as specified by NASA.',
    glossaryTitle: 'Multilingual Science Glossary',
    glossaryDescription: 'A dictionary of meteorology, geophysics, astronomy, and space mission terms to help readers understand technical words like light rain, kosame, NEO, APOD, Martian sol, and space weather.',
    glossaryBadge: 'BMKG + NASA',
    openGlossary: 'Open Glossary',
    backToGlossary: '← Back to Glossary',
    definitionLabel: 'Definition',
    exampleLabel: 'Example',
    richDiscussion: 'Scientific Discussion',
    translationsLabel: 'Translations',
    updatedAtLabel: 'Updated:',
    sourceLabel: 'Source:',
    glossaryError: 'Term not found.',
    // FireballEonetSection
    earthMonitorBadge: '🌍 Earth Monitoring from Space',
    earthMonitorTitle: 'Natural Events & Fireballs',
    earthMonitorDesc: 'Real-time data from NASA JPL Fireball API and NASA EONET Earth Observatory — monitoring Earth live from space.',
    fireballTab: '🔥 Fireball',
    eonetTab: '🌍 Natural Events',
    liveFireballFeed: 'Live JPL Fireball Feed',
    noFireballData: 'No recent fireball data available.',
    viewAllMonitoring: 'View all in Monitoring →',
    noFireballArticles: 'No Fireball articles yet.',
    noEonetArticles: 'No Natural Events articles yet.',
    autoCronFill: 'Automatic cron will fill articles daily.',
    viewAllFireball: 'View All Fireball Articles →',
    viewAllEonet: 'View All Natural Events Articles →',
    // List page UI
    totalArticles: 'Total: {n} Articles',
    searchFireball: 'Search fireball articles...',
    searchEonet: 'Search natural events articles...',
    searchApod: 'Search space photos, dates, or topics...',
    apodGalleryBadge: 'NASA Astronomy Picture of the Day (APOD)',
    apodGalleryTitle: 'Space Photo Gallery',
    apodGalleryDesc: 'Explore the beauty of the universe through NASA\'s curated daily astronomy images, complete with AI-translated scientific explanations.',
    apodShowingOf: 'Showing {filtered} of {total} archived photos.',
    apodNoResults: 'No space photos match your search.',
    viewDetail: 'View Detail →',
    readMore2: 'Read More →',
    fireballListBadge: '🔥 Real-Time NASA/JPL Fireball Data API',
    fireballListTitle: 'Fireball Reports',
    fireballListDesc: 'Popular science analysis of fireball events — meteor fireballs detected entering Earth\'s atmosphere based on NASA/JPL global infrared sensor data.',
    noFireballArticlesList: 'No Fireball articles yet',
    noFireballCron: 'Use the Admin menu to trigger automatic Fireball article publishing.',
    noFireballMatch: 'No articles match your search.',
    kometListBadge: '☄️ Education & Space Rock News',
    kometListTitle: 'Comet & Asteroid Articles',
    kometListDesc: 'Popular science analysis, NASA NeoWs near-Earth object tracking, and real-time asteroid education articles.',
    noKometArticlesList: 'No comet & asteroid articles yet',
    noKometCron: 'Use the Admin menu to trigger automatic comet article publishing.',
    noKometMatch: 'No articles match your search.',
    eonetListBadge: '🌍 Real-Time NASA EONET v3 Earth Observatory',
    eonetListTitle: 'Active Natural Events',
    eonetListDesc: 'Monitor active natural events on Earth — volcanoes, wildfires, severe storms, and other natural phenomena tracked by NASA from space.',
    noEonetArticlesList: 'No Natural Events articles yet',
    noEonetCron: 'Use the Admin menu to trigger automatic EONET article publishing.',
    noEonetMatch: 'No articles match your search.',
    blogListTitle: 'Astronomy & Meteorite Blog',
    blogListDesc: 'Latest science news, guides to identifying sky rocks, and interesting astronomy trivia.',
    // ArticleActions
    ttsPlay: '🔊 Play AI Audio',
    ttsStop: '⏹️ Stop Audio',
    downloadPdf: '📥 Download PDF',
    downloadShareCard: '📸 Download Share Card',
    shareLabel: 'SHARE:',
    copyLink: '🔗 Copy',
    linkCopied: 'Article link copied successfully!',
    // Article back nav
    backToBlog: '← Back to Article List',
    backToFireball: '← Back to Fireball',
    backToEonet: '← Back to Natural Events',
    backToKomet: '← Back to Comet Articles',
    backToMars: '← Back to Mars Articles',
    backToApod: '← Back to APOD Gallery',
    releaseDate: 'Release Date',
    copyrightLabel: 'Copyright / Source',
    scientificExplanation: 'Scientific Explanation',
    originalExplanation: 'Original English Explanation',
    apodError: 'Space photo not found or date format is incorrect.',
    backToAstronaut: '← Back to Astronaut Profiles',
    astroError: 'Astronaut profile not found.',
    astroStatusActive: 'On Mission',
    astroStatusUpcoming: 'Upcoming Mission',
    astroStatusReturned: 'Returned',
    astroCountry: 'Country',
    astroAgency: 'Agency',
    astroMissionDuration: 'Mission Duration',
    astroUpcomingText: 'Scheduled',
    daysUnit: 'Days',
    astroBioTitle: 'Biography & Mission',
    meteorError: 'Meteorite data not found.',
    backToCatalog: 'Back to Catalog',
    backToEncyclopedia: '← Back to Encyclopedia Catalog',
    physicalSpec: 'Physical Specifications',
    rockName: 'Rock Name:',
    rockType: 'Type / Class:',
    estimatedMass: 'Estimated Mass:',
    foundYear: 'Year Found:',
    latitudeLabel: 'Latitude Coordinate:',
    longitudeLabel: 'Longitude Coordinate:',
    descriptionHistory: 'Description & Historical Analysis',
    landingLocation: 'Geographical Landing Location',
    impactCoordinates: 'Impact Coordinates:',
    openInGoogleMaps: 'Open in Google Maps →',
    articleNotFound: 'Article not found.',
    visitWebsite: 'Visit Our Site',
    // Star Map / Langit Malam
    starMapBadge: '🌠 Interactive Star Map',
    starMapTitle: 'Night Sky',
    starMapSubtitle: 'Allow GPS location access or choose your city to dynamically navigate the star constellation map tonight.',
    gpsDetecting: 'Detecting Location...',
    gpsDetected: 'GPS Detected:',
    useGpsBtn: '📍 Use My GPS Location',
    gpsNotSupported: 'Your browser does not support GPS.',
    gpsErrorDenied: 'GPS access denied or unavailable. Please choose a city manually.',
    orSelectCity: 'OR SELECT CITY',
    orManualInput: 'OR MANUAL INPUT',
    latLabel: 'Latitude',
    lonLabel: 'Longitude',
    latPlaceholder: 'Example: -6.2088',
    lonPlaceholder: 'Example: 106.8456',
    latError: 'Latitude must be a number between -90 and 90.',
    lonError: 'Longitude must be a number between -180 and 180.',
    applyCoordsBtn: 'Apply Custom Coordinates',
    nightSkyAt: 'Night Sky at',
    openFullScreen: 'Open Fullscreen ↗',
    starMapProvidedBy: 'Star map provided by',
    starMapInstructions: '🖱️ Click & drag to rotate the sky • Scroll to zoom',
    constellationTitle: 'Constellations Tonight',
    constellationDesc: 'Identify visible constellations from your city tonight based on real-time position and time.',
    moonPhaseTitle: 'Moon Phase',
    moonPhaseDesc: 'Monitor the moon phase today and predict upcoming phases for the best astronomical observation planning.',
    visiblePlanetsTitle: 'Visible Planets',
    visiblePlanetsDesc: 'Know which planets are visible with the naked eye or telescope from your location tonight.',
    earthMonitorWidget: 'Live Earth Data for the Night Sky Community',
    earthMonitorSubtitle: 'Earth Monitoring Simulator',
    tabQuake: '🌋 Latest Quakes',
    tabWeather: '🌧️ Weather & Rain',
    tabEnergy: '☀️ Wind & Solar',
    quakePanelSub: 'Live JSON BMKG TEWS',
    quakePanelTitle: 'Latest Earthquake',
    quakeRefreshTitle: 'Reload BMKG data',
    quakeMagnitude: 'Magnitude',
    quakeDepth: 'Depth',
    quakeRegion: 'Region',
    quakeTsunami: 'Tsunami Potential',
    quakeLoadingRegion: 'Loading region data...',
    quakeUpdate: 'Updated:',
    quakeIndependent: 'Independent fetch from BMKG.',
    weatherSub: 'Real-time weather data',
    weatherTitle: 'Weather & Sky Conditions',
    weatherGpsDetecting: 'Automatically detecting your location via GPS/Wi-Fi...',
    weatherGpsFound: 'Location detected:',
    weatherGpsDenied: 'Location permission denied. Use the manual search form below.',
    weatherGpsError: 'Failed to auto-detect location. Try searching manually.',
    weatherOwLoading: 'Fetching actual weather data from OpenWeather...',
    weatherOwActual: '🌤️ OpenWeather — Live Data',
    weatherOwError: 'OpenWeather unavailable.',
    weatherOwCacheNote: 'Source: OpenWeather API · 15-min cache',
    weatherSearchLabel: 'Search area, city, village, or coordinates',
    weatherSearchPlaceholder: 'Jakarta, -6.2088, 106.8456',
    weatherSearchBtn: 'Search',
    weatherSearchHint: 'Enter an area name, street, village, district, city, or latitude/longitude coordinates.',
    weatherSearchMin: 'Enter at least 3 characters or full coordinates.',
    weatherSearchSuccess: 'Real-time data for {label} loaded.',
    weatherSearchFail: 'Failed to find location.',
    weatherSimResult: 'Search result — BMKG Simulator',
    weatherTemp: 'Temperature',
    weatherRain: 'Rain',
    weatherHumidity: 'Humidity',
    weatherCondition: 'Condition',
    weatherRainChance: 'rain chance',
    weatherPrecipitation: 'precipitation',
    weatherFeelsLike: 'Feels like',
    weatherHumidityLabel: 'Humidity',
    weatherWind: 'Wind',
    weatherClouds: 'Clouds',
    weatherHumidityHigh: 'Humid',
    weatherHumidityNormal: 'Normal',
    weatherHumidityLow: 'Dry',
    weatherCloudsLow: 'Clear',
    weatherCloudsMid: 'Cloudy',
    weatherCloudsHigh: 'Overcast',
    weatherTempCold: 'Cool',
    weatherTempNormal: 'Normal',
    weatherTempHot: 'Hot',
    weatherRainLow: 'Low',
    weatherRainMid: 'Moderate',
    weatherRainHigh: 'High',
    weatherIntensity: 'Rain intensity',
    weatherCityTonight: 'Air Temp in {city} Tonight:',
    energySub: 'RE-Atlas potential simulator',
    energyTitle: 'Wind & Solar Energy',
    energyGpsFound: 'Location auto-detected:',
    energyGpsDenied: 'Location permission denied. Use the manual search form below.',
    energyGpsError: 'Failed to auto-detect location. Try searching manually.',
    energyRealtimeResult: 'Real-time search result',
    energyWind10m: 'Wind at 10m',
    energyWindDir: 'Wind Direction',
    energySolar: 'Solar Radiation',
    energySolarNote: 'This is real-time surface weather from Open-Meteo, useful as an initial indicator of local wind and sun conditions.',
    energySolarLabel: 'Solar',
    energyWindLabel: 'Wind',
    energyTopSolar: 'Solar Radiation:',
    earthDataSource: 'Live data provided by BMKG, Open-Meteo, and ESDM RE-Atlas. This widget runs independently of NASA_API_KEY.',
    pushTitle: 'Live Space Notifications',
    pushDesc: 'Enable browser notifications for live asteroid flybys, BMKG earthquakes, and NASA APOD gallery.',
    pushDismiss: 'Later',
    pushAccept: 'Enable',
    pushLoading: 'Enabling...',
    astroLiveArchive: 'Live & mission archives',
    astroPageTitle: 'Humans in Space Database',
    astroPageDesc1: 'This page summarizes the profiles of astronauts, cosmonauts, and taikonauts in three groups.',
    astroPageDesc2: 'Active crew members typically live on the ISS or Tiangong for months to run microgravity experiments.',
    astroTotalProfiles: 'Total Profiles',
    astroActive: 'Active',
    astroUpcomingStat: 'Upcoming',
    astroAlumni: 'Alumni',
    astroTabActive: 'In Space Now',
    astroTabActiveTitle: 'Active Crew Members',
    astroTabActiveDesc: 'Astronauts, cosmonauts, and taikonauts currently on active missions in Earth orbit.',
    astroTabUpcoming: 'Upcoming Missions',
    astroTabUpcomingTitle: 'Crews Scheduled to Launch',
    astroTabUpcomingDesc: 'Crew members scheduled for upcoming space flights to space stations or exploration missions.',
    astroTabReturned: 'Space Heroes',
    astroTabReturnedTitle: 'Alumni and Returned Crews',
    astroTabReturnedDesc: 'Archive of crew members who served on the ISS, Tiangong, or other orbit missions and returned to Earth.',
    astroNoData: 'No data available for this category.',
    readFullBio: 'View Full Biography',
    updatedAt: 'Updated',
    missionLabel: 'Mission',
  },
  ms: {
    loading: 'Memuat...',
    readMore: 'Baca Selanjutnya',
    readDetail: 'Lihat Butiran',
    previous: 'Sebelumnya',
    next: 'Seterusnya',
    page: 'Halaman',
    all: 'Semua',
    total: 'Jumlah',
    article: 'Artikel',
    statsMeteorites: 'Meteorit Terdokumen di Dunia',
    statsCollectors: 'Pengumpul Indonesia',
    statsAsteroids: 'Asteroid Dekat Bumi Hari Ini',
    statsAstronauts: 'Angkasawan di Orbit Saat Ini',
    objectUnit: 'Objek',
    crewUnit: 'Kru',
    dailyUpdate: 'Kemas Kini Harian',
    skyObjectToday: 'Objek Langit Hari Ini',
    nasaDailyData: 'Data langsung NASA - dikemas kini setiap hari',
    latestEarthPhoto: 'Memuat foto Bumi terkini...',
    epicUnavailable: 'Foto Bumi EPIC tidak tersedia saat ini',
    epicMonitor: 'Monitor Satelit EPIC',
    epicDescription: 'Foto Bumi terkini yang diambil oleh kamera EPIC NASA dari jarak 1.5 juta km, memperlihatkan sisi Bumi yang disinari Matahari.',
    latitude: 'Latitud',
    longitude: 'Longitud',
    latest: 'Terkini',
    monitorEpic: 'Pantau EPIC',
    viewAllMeteorCatalog: 'Lihat Semua Katalog Meteorit',
    blogLatest: 'Artikel Astronomi Terkini',
    newsletterTitle: 'Langgan Berita',
    newsletterDescription: 'Masukkan email anda untuk menerima notifikasi percuma tentang kejadian meteor baharu dan artikel astronomi terus ke peti masuk.',
    newsletterSuccess: 'Terima kasih! Anda telah melanggan newsletter kami.',
    emailPlaceholder: 'Masukkan alamat email anda',
    subscribeNow: 'Langgan Sekarang',
    blogTitle: 'Blog Astronomi & Meteorit',
    blogDescription: 'Berita sains terkini, panduan mengenal batu langit, dan trivia astronomi menarik.',
    searchScience: 'Cari artikel sains...',
    noArticles: 'Belum ada artikel',
    noGeneratedArticles: 'Artikel AI belum dijana. Buka Admin - Pengurusan Artikel - klik "Buat Artikel AI".',
    noSearchMatch: 'Tiada artikel yang sepadan dengan carian anda.',
    cometBadge: 'Edukasi & Kabar Batuan Angkasa',
    cometTitle: 'Artikel Komet & Asteroid',
    cometDescription: 'Analisis sains popular, jejak objek dekat Bumi NASA NeoWs, dan artikel edukasi asteroid real-time.',
    searchComet: 'Cari artikel komet & asteroid...',
    noCometArticles: 'Belum ada artikel komet & asteroid',
    noCometGenerated: 'Gunakan menu Admin untuk memicu rilis automatik artikel komet.',
    redPlanet: 'Planet Merah',
    marsLatest: 'Artikel Mars Terkini',
    marsDescription: 'Kabar rover, geologi, cuaca ekstrem, dan masa depan manusia di Mars daripada arkib Meteorit Indonesia.',
    viewAllMars: 'Lihat Semua Artikel Mars',
    readMars: 'Baca Artikel Mars',
    communityTitle: 'Meteor atau Bukan?',
    communityP1: 'Adakah anda menemukan batu unik di alam dan ragu sama ada ia batuan Bumi biasa atau meteorit angkasa?',
    communityP2: 'Muat naik foto batu temuan anda ke forum dan minta penilaian ahli astronomi serta komuniti melalui sistem undian interaktif.',
    askForum: 'Tanya di Forum',
    welcome: 'Selamat Datang',
    forumVisit: 'Kunjungi forum diskusi untuk menulis soalan anda',
    googleLoginPrompt: 'Masuk dengan Akaun Google untuk menyertai',
    googleLogin: 'Masuk dengan Google',
    donationTitle: 'Sokong Eksplorasi Sains & Komuniti',
    donationDescription: 'Meteorit Indonesia ialah platform nirlaba yang disokong komuniti. Donasi anda membantu kos hosting, API NASA, dan pembangunan riset edukasi angkasa.',
    donationStepEmail: 'Langkah 1: Masukkan Alamat Email',
    donationStepAmount: 'Langkah 2: Pilih Jumlah Donasi',
    donationCustom: 'Masukkan jumlah donasi khusus',
    donationButton: 'Kirim Donasi via Midtrans',
    donationProcessing: 'Memproses Pembayaran...',
    liveSpaceData: 'Data Angkasa Langsung',
    missionControlTitle: 'Pusat Kawalan Misi Angkasa',
    missionControlDesc: 'Data real-time misi orbit Bumi dan stesen angkasa',
    
    // New Translations
    nasaApodLabel: '📡 NASA APOD',
    nasaEpicLabel: '🌍 NASA EPIC',
    apodTitle: 'Astronomy Picture of the Day',
    epicTitle: 'Earth Polychromatic Imaging Camera',
    upcomingLaunch: 'Pelancaran Terdekat',
    scientificMission: 'Misi Sains',
    goForLaunch: 'Terjadual / Bersedia Meluncur',
    countdownDays: 'Hari',
    countdownHours: 'Jam',
    countdownMinutes: 'Minit',
    countdownSeconds: 'Saat',
    countingDown: 'Mengira mundur pelancaran...',
    launchDataSource: 'Sumber data: Launch Library API →',
    issTrackerTitle: 'Live ISS Tracker',
    issActive: 'Aktif',
    issMapUnavailable: 'Peta tidak tersedia',
    issUpdateInterval: 'Dikemas kini automatik setiap 5 saat',
    activeAstronauts: 'Kru di Orbit Saat Ini',
    astronautSub: 'angkasawan, kosmonot, dan taikonaut aktif',
    viewAllAstronauts: '👨‍🚀 Lihat Semua Profil Angkasawan →',
    astronautDataSource: 'Sumber data: Dataset dalaman & Open Notify →',
    donationEmailAlert: 'Sila masukkan email anda terlebih dahulu untuk bukti derma.',
    donationSuccessAlert: 'Derma berjaya! Terima kasih atas sokongan anda.',
    donationPendingAlert: 'Pembayaran tertunda, sila selesaikan pembayaran anda.',
    donationFailAlert: 'Pembayaran derma gagal.',
    donationStartFailAlert: 'Gagal memulakan pembayaran derma. Sila cuba lagi.',
    dataAttribution: '🛰️ Atribusi Data:',
    dataProvidedBy: 'Data di tapak ini disediakan oleh',
    freeToUse: 'bebas digunakan mengikut',
    nasaPolicy: 'dasar NASA',
    photoCopyrightNote: 'Hak cipta foto APOD dikreditkan kepada pemilik masing-masing seperti yang dinyatakan oleh NASA.',
    glossaryTitle: 'Glosarium Sains Multi Bahasa',
    glossaryDescription: 'Kamus istilah meteorologi, geofizik, astronomi, dan misi angkasa untuk membantu pembaca memahami perkataan teknikal seperti hujan ringan, kosame, NEO, APOD, sol Marikh, dan cuaca angkasa.',
    glossaryBadge: 'BMKG + NASA',
    openGlossary: 'Buka Glosarium',
    backToGlossary: '← Kembali ke Glosarium',
    definitionLabel: 'Definisi',
    exampleLabel: 'Contoh',
    richDiscussion: 'Perbincangan Saintifik',
    translationsLabel: 'Terjemahan',
    updatedAtLabel: 'Dikemas kini:',
    sourceLabel: 'Sumber:',
    glossaryError: 'Istilah tidak ditemui.',
    // FireballEonetSection
    earthMonitorBadge: '🌍 Pemantauan Bumi dari Angkasa',
    earthMonitorTitle: 'Peristiwa Alam & Bola Api',
    earthMonitorDesc: 'Data masa nyata daripada NASA JPL Fireball API dan NASA EONET Earth Observatory — pemantauan Bumi langsung dari angkasa.',
    fireballTab: '🔥 Bola Api',
    eonetTab: '🌍 Peristiwa Alam',
    liveFireballFeed: 'Suapan JPL Bola Api Langsung',
    noFireballData: 'Tiada data bola api terkini.',
    viewAllMonitoring: 'Lihat semua di Pemantauan →',
    noFireballArticles: 'Belum ada artikel Bola Api.',
    noEonetArticles: 'Belum ada artikel Peristiwa Alam.',
    autoCronFill: 'Cron automatik akan mengisi artikel setiap hari.',
    viewAllFireball: 'Lihat Semua Artikel Bola Api →',
    viewAllEonet: 'Lihat Semua Artikel Peristiwa Alam →',
    // List page UI
    totalArticles: 'Jumlah: {n} Artikel',
    searchFireball: 'Cari artikel bola api...',
    searchEonet: 'Cari artikel peristiwa alam...',
    searchApod: 'Cari foto angkasa, tarikh, atau topik...',
    apodGalleryBadge: 'NASA Astronomy Picture of the Day (APOD)',
    apodGalleryTitle: 'Galeri Foto Angkasa',
    apodGalleryDesc: 'Jelajahi keindahan alam semesta melalui kurasi gambar astronomi harian rasmi NASA, lengkap dengan penjelasan saintifik yang diterjemahkan menggunakan AI.',
    apodShowingOf: 'Menunjukkan {filtered} daripada {total} foto arkib.',
    apodNoResults: 'Tiada foto angkasa yang sepadan dengan carian anda.',
    viewDetail: 'Lihat Butiran →',
    readMore2: 'Baca Selanjutnya →',
    fireballListBadge: '🔥 Data Masa Nyata NASA/JPL Fireball Data API',
    fireballListTitle: 'Laporan Bola Api (Fireball)',
    fireballListDesc: 'Analisis sains popular tentang peristiwa bola api — bola api meteor yang dikesan memasuki atmosfera Bumi berdasarkan data sensor inframerah global NASA/JPL.',
    noFireballArticlesList: 'Belum ada artikel Bola Api',
    noFireballCron: 'Gunakan menu Admin untuk memicu rilis automatik artikel Bola Api.',
    noFireballMatch: 'Tiada artikel yang sepadan dengan carian anda.',
    kometListBadge: '☄️ Edukasi & Kabar Batuan Angkasa',
    kometListTitle: 'Artikel Komet & Asteroid',
    kometListDesc: 'Analisis sains popular, jejak objek dekat Bumi NASA NeoWs, dan artikel edukasi asteroid masa nyata.',
    noKometArticlesList: 'Belum ada artikel komet & asteroid',
    noKometCron: 'Gunakan menu Admin untuk memicu rilis automatik artikel komet.',
    noKometMatch: 'Tiada artikel yang sepadan dengan carian anda.',
    eonetListBadge: '🌍 Data Masa Nyata NASA EONET v3 Earth Observatory',
    eonetListTitle: 'Peristiwa Alam Aktif',
    eonetListDesc: 'Pantau peristiwa alam yang sedang aktif di Bumi — gunung berapi, kebakaran hutan, ribut dahsyat, dan fenomena alam lain yang dipantau NASA dari angkasa.',
    noEonetArticlesList: 'Belum ada artikel Peristiwa Alam',
    noEonetCron: 'Gunakan menu Admin untuk memicu rilis automatik artikel EONET.',
    noEonetMatch: 'Tiada artikel yang sepadan dengan carian anda.',
    blogListTitle: 'Blog Astronomi & Meteorit',
    blogListDesc: 'Berita sains terkini, panduan mengenal batu langit, dan trivia astronomi menarik.',
    // ArticleActions
    ttsPlay: '🔊 Main Suara AI',
    ttsStop: '⏹️ Henti Suara',
    downloadPdf: '📥 Muat Turun PDF',
    downloadShareCard: '📸 Muat Turun Kad Kongsi',
    shareLabel: 'KONGSI:',
    copyLink: '🔗 Salin',
    linkCopied: 'Pautan artikel berjaya disalin!',
    // Article back nav
    backToBlog: '← Kembali ke Senarai Artikel',
    backToFireball: '← Kembali ke Bola Api',
    backToEonet: '← Kembali ke Peristiwa Alam',
    backToKomet: '← Kembali ke Artikel Komet',
    backToMars: '← Kembali ke Artikel Marikh',
    backToApod: '← Kembali ke Galeri APOD',
    releaseDate: 'Tarikh Rilis',
    copyrightLabel: 'Hak Cipta / Sumber',
    scientificExplanation: 'Penjelasan Saintifik',
    originalExplanation: 'Penjelasan Asal Bahasa Inggeris',
    apodError: 'Foto angkasa tidak ditemui atau format tarikh salah.',
    backToAstronaut: '← Kembali ke Profil Angkasawan',
    astroError: 'Profil angkasawan tidak ditemui.',
    astroStatusActive: 'Sedang Bertugas',
    astroStatusUpcoming: 'Misi Mendatang',
    astroStatusReturned: 'Sudah Kembali',
    astroCountry: 'Asal Negara',
    astroAgency: 'Agensi',
    astroMissionDuration: 'Durasi Misi',
    astroUpcomingText: 'Terjadwal',
    daysUnit: 'Hari',
    astroBioTitle: 'Biografi & Misi',
    meteorError: 'Data meteorit tidak ditemui.',
    backToCatalog: 'Kembali ke Katalog',
    backToEncyclopedia: '← Kembali ke Katalog Ensiklopedia',
    physicalSpec: 'Spesifikasi Fizikal',
    rockName: 'Nama Batuan:',
    rockType: 'Jenis / Kelas:',
    estimatedMass: 'Anggaran Massa:',
    foundYear: 'Tahun Ditemui:',
    latitudeLabel: 'Koordinat Latitud:',
    longitudeLabel: 'Koordinat Longitud:',
    descriptionHistory: 'Deskripsi & Analisis Sejarah',
    landingLocation: 'Lokasi Geografi Pendaratan',
    impactCoordinates: 'Koordinat Jatuh:',
    openInGoogleMaps: 'Buka di Google Maps →',
    articleNotFound: 'Artikel tidak ditemui.',
    // Star Map / Langit Malam
    starMapBadge: '🌠 Peta Bintang Interaktif',
    starMapTitle: 'Langit Malam',
    starMapSubtitle: 'Benarkan akses lokasi GPS atau pilih bandar anda untuk menavigasi peta buruj bintang malam ini secara dinamik.',
    gpsDetecting: 'Mengesan Lokasi...',
    gpsDetected: 'GPS Dikesan:',
    useGpsBtn: '📍 Gunakan Lokasi GPS Saya',
    gpsNotSupported: 'Pelayar anda tidak menyokong GPS.',
    gpsErrorDenied: 'Akses GPS ditolak atau tidak tersedia. Sila pilih bandar secara manual.',
    orSelectCity: 'ATAU PILIH BANDAR',
    orManualInput: 'ATAU INPUT MANUAL',
    latLabel: 'Latitude (Lintang)',
    lonLabel: 'Longitude (Bujur)',
    latPlaceholder: 'Contoh: -6.2088',
    lonPlaceholder: 'Contoh: 106.8456',
    latError: 'Latitude mestilah nombor antara -90 dan 90.',
    lonError: 'Longitude mestilah nombor antara -180 dan 180.',
    applyCoordsBtn: 'Terapkan Koordinat Kustom',
    nightSkyAt: 'Langit Malam di',
    openFullScreen: 'Buka Skrin Penuh ↗',
    starMapProvidedBy: 'Peta bintang disediakan oleh',
    starMapInstructions: '🖱️ Klik & seret untuk memutar langit • Tatal untuk zum',
    constellationTitle: 'Buruj Malam Ini',
    constellationDesc: 'Kenal pasti buruj yang kelihatan dari bandar anda malam ini berdasarkan kedudukan dan masa nyata.',
    moonPhaseTitle: 'Fasa Bulan',
    moonPhaseDesc: 'Pantau fasa bulan hari ini dan ramal fasa seterusnya untuk perancangan pemerhatian astronomi terbaik.',
    visiblePlanetsTitle: 'Planet yang Kelihatan',
    visiblePlanetsDesc: 'Ketahui planet mana yang boleh diperhatikan dengan mata kasar atau teleskop dari lokasi anda malam ini.',
    earthMonitorWidget: 'Data Bumi Langsung untuk Komuniti Langit Malam',
    earthMonitorSubtitle: 'Earth Monitoring Simulator',
    tabQuake: '🌋 Gempa Terkini',
    tabWeather: '🌧️ Cuaca & Hujan',
    tabEnergy: '☀️ Angin & Solar',
    quakePanelSub: 'Live JSON BMKG TEWS',
    quakePanelTitle: 'Gempa Bumi Terkini',
    quakeRefreshTitle: 'Muat semula data BMKG',
    quakeMagnitude: 'Magnitud',
    quakeDepth: 'Kedalaman',
    quakeRegion: 'Kawasan',
    quakeTsunami: 'Potensi Tsunami',
    quakeLoadingRegion: 'Memuatkan data kawasan...',
    quakeUpdate: 'Dikemas kini:',
    quakeIndependent: 'Pengambilan bebas dari BMKG.',
    weatherSub: 'Data cuaca masa nyata',
    weatherTitle: 'Info Cuaca & Kondisi Langit',
    weatherGpsDetecting: 'Mengesan lokasi anda secara automatik melalui GPS/Wi-Fi...',
    weatherGpsFound: 'Lokasi dikesan:',
    weatherGpsDenied: 'Kebenaran lokasi ditolak. Gunakan borang carian manual di bawah.',
    weatherGpsError: 'Gagal mengesan lokasi automatik. Cuba cari secara manual.',
    weatherOwLoading: 'Mengambil data cuaca sebenar dari OpenWeather...',
    weatherOwActual: '🌤️ OpenWeather — Data Sebenar',
    weatherOwError: 'OpenWeather tidak tersedia.',
    weatherOwCacheNote: 'Sumber: OpenWeather API · Cache 15 minit',
    weatherSearchLabel: 'Cari alamat, kawasan, kampung, bandar, atau koordinat',
    weatherSearchPlaceholder: 'Kuala Lumpur, -6.2088, 106.8456',
    weatherSearchBtn: 'Cari',
    weatherSearchHint: 'Masukkan nama kawasan, jalan, kampung, daerah, bandar, atau koordinat.',
    weatherSearchMin: 'Masukkan sekurang-kurangnya 3 aksara atau koordinat penuh.',
    weatherSearchSuccess: 'Data masa nyata untuk {label} berjaya dimuatkan.',
    weatherSearchFail: 'Gagal mencari lokasi.',
    weatherSimResult: 'Hasil carian — Simulator BMKG',
    weatherTemp: 'Suhu',
    weatherRain: 'Hujan',
    weatherHumidity: 'Kelembapan',
    weatherCondition: 'Keadaan',
    weatherRainChance: 'peluang hujan',
    weatherPrecipitation: 'presipitasi',
    weatherFeelsLike: 'Rasa seperti',
    weatherHumidityLabel: 'Kelembapan',
    weatherWind: 'Angin',
    weatherClouds: 'Awan',
    weatherHumidityHigh: 'Lembap',
    weatherHumidityNormal: 'Normal',
    weatherHumidityLow: 'Kering',
    weatherCloudsLow: 'Cerah',
    weatherCloudsMid: 'Berawan',
    weatherCloudsHigh: 'Mendung',
    weatherTempCold: 'Sejuk',
    weatherTempNormal: 'Normal',
    weatherTempHot: 'Panas',
    weatherRainLow: 'Rendah',
    weatherRainMid: 'Sederhana',
    weatherRainHigh: 'Tinggi',
    weatherIntensity: 'Intensiti hujan',
    weatherCityTonight: 'Suhu Udara {city} Malam Ini:',
    energySub: 'Simulator potensi RE-Atlas',
    energyTitle: 'Tenaga Angin & Solar',
    energyGpsFound: 'Lokasi dikesan automatik:',
    energyGpsDenied: 'Kebenaran lokasi ditolak. Gunakan borang carian manual.',
    energyGpsError: 'Gagal mengesan lokasi automatik. Cuba cari secara manual.',
    energyRealtimeResult: 'Hasil carian masa nyata',
    energyWind10m: 'Angin 10m',
    energyWindDir: 'Arah Angin',
    energySolar: 'Sinaran Suria',
    energySolarNote: 'Ini adalah bacaan cuaca permukaan masa nyata dari Open-Meteo, berguna sebagai petunjuk awal keadaan angin dan matahari setempat.',
    energySolarLabel: 'Solar',
    energyWindLabel: 'Angin',
    energyTopSolar: 'Sinaran Matahari:',
    earthDataSource: 'Data langsung disediakan oleh BMKG, Open-Meteo, dan ESDM RE-Atlas. Widget ini berjalan bebas dari NASA_API_KEY.',
    visitWebsite: 'Lawati Laman Kami',
    pushTitle: 'Notifikasi Angkasa Langsung',
    pushDesc: 'Aktifkan pemberitahuan penyemak imbas untuk lintas dekat asteroid, gempa bumi BMKG dan galeri APOD NASA.',
    pushDismiss: 'Nanti Sahaja',
    pushAccept: 'Aktifkan',
    pushLoading: 'Mengaktifkan...',
    astroLiveArchive: 'Live & arkib misi',
    astroPageTitle: 'Pangkalan Data Manusia di Angkasa',
    astroPageDesc1: 'Halaman ini merangkum profil angkasawan, kosmonot, dan taikonaut dalam tiga kumpulan.',
    astroPageDesc2: 'Kru aktif biasanya tinggal di ISS atau Tiangong selama berbulan-bulan untuk menjalankan eksperimen mikrograviti.',
    astroTotalProfiles: 'Jumlah Profil',
    astroActive: 'Aktif',
    astroUpcomingStat: 'Mendatang',
    astroAlumni: 'Alumni',
    astroTabActive: 'Di Angkasa Sekarang',
    astroTabActiveTitle: 'Ahli Kru Aktif',
    astroTabActiveDesc: 'Angkasawan, kosmonot, dan taikonaut yang kini dalam misi aktif di orbit Bumi.',
    astroTabUpcoming: 'Misi Mendatang',
    astroTabUpcomingTitle: 'Kru Dijadualkan Berlepas',
    astroTabUpcomingDesc: 'Kru yang dijadualkan untuk penerbangan angkasa lepas akan datang ke stesen angkasa atau misi penerokaan.',
    astroTabReturned: 'Wira Angkasa',
    astroTabReturnedTitle: 'Alumni dan Kru yang Telah Kembali',
    astroTabReturnedDesc: 'Arkib ahli kru yang pernah berkhidmat di ISS, Tiangong, atau misi orbit lain dan kembali ke Bumi.',
    astroNoData: 'Tiada data untuk kategori ini.',
    readFullBio: 'Lihat Biografi Penuh',
    updatedAt: 'Dikemas kini',
    missionLabel: 'Misi',
  },
  zh: {
    loading: '加载中...',
    readMore: '阅读全文',
    readDetail: '查看详情',
    previous: '上一页',
    next: '下一页',
    page: '页面',
    all: '全部',
    total: '总数',
    article: '文章',
    statsMeteorites: '全球已记录陨石',
    statsCollectors: '印尼收藏者',
    statsAsteroids: '今日近地小行星',
    statsAstronauts: '当前在轨宇航员',
    objectUnit: '个天体',
    crewUnit: '名成员',
    dailyUpdate: '每日更新',
    skyObjectToday: '今日天体',
    nasaDailyData: 'NASA 实时数据 - 每日更新',
    latestEarthPhoto: '正在加载最新地球照片...',
    epicUnavailable: 'EPIC 地球照片暂不可用',
    epicMonitor: 'EPIC 卫星监测',
    epicDescription: 'NASA EPIC 从 150 万公里外拍摄的最新地球照片，展示被阳光照亮的一面。',
    latitude: '纬度',
    longitude: '经度',
    latest: '最新',
    monitorEpic: '查看 EPIC',
    viewAllMeteorCatalog: '查看全部陨石目录',
    blogLatest: '最新天文文章',
    newsletterTitle: '订阅新闻',
    newsletterDescription: '输入邮箱，免费接收新流星事件和天文文章通知。',
    newsletterSuccess: '谢谢！你已订阅我们的新闻通讯。',
    emailPlaceholder: '输入你的邮箱地址',
    subscribeNow: '立即订阅',
    blogTitle: '天文与陨石博客',
    blogDescription: '最新科学新闻、天石识别指南和有趣的天文知识。',
    searchScience: '搜索科学文章...',
    noArticles: '暂无文章',
    noGeneratedArticles: 'AI 文章尚未生成。请打开 Admin - Article Management - 点击 Create AI Article。',
    noSearchMatch: '没有符合搜索条件的文章。',
    cometBadge: '太空岩石新闻与教育',
    cometTitle: '彗星与小行星文章',
    cometDescription: '科普 analysis、NASA NeoWs 近地天体追踪，以及实时小行星教育文章。',
    searchComet: '搜索彗星与小行星文章...',
    noCometArticles: '暂无彗星与小行星文章',
    noCometGenerated: '请在 Admin 菜单触发彗星文章自动发布。',
    redPlanet: '红色星球',
    marsLatest: '最新火星文章',
    marsDescription: '来自 Meteorit Indonesia 文章库的探测车、地质、极端天气和人类火星未来资讯。',
    viewAllMars: '查看全部火星文章',
    readMars: '阅读火星文章',
    communityTitle: '是流星石吗？',
    communityP1: '你是否在户外发现了不寻常的石头，并想知道它是普通地球岩石还是太空陨石？',
    communityP2: '将发现照片上传到论坛，请天文学专家和社区成员通过互动投票协助判断。',
    askForum: '在论坛提问',
    welcome: '欢迎',
    forumVisit: '前往讨论论坛提出你的问题',
    googleLoginPrompt: '使用 Google 登录以参与',
    googleLogin: '使用 Google 登录',
    donationTitle: '支持科学探索与社区',
    donationDescription: 'Meteorit Indonesia 是由社区支持的非营利平台。你的捐助将帮助支付托管、NASA API 和太空教育研究费用。',
    donationStepEmail: '步骤 1：输入邮箱地址',
    donationStepAmount: '步骤 2：选择捐助金额',
    donationCustom: '输入自定义捐助金额',
    donationButton: '通过 Midtrans 捐助',
    donationProcessing: '正在处理付款...',
    liveSpaceData: '实时太空数据',
    missionControlTitle: '太空任务控制中心',
    missionControlDesc: '地球轨道任务和空间站实时数据',
    
    // New Translations
    nasaApodLabel: '📡 NASA APOD',
    nasaEpicLabel: '🌍 NASA EPIC',
    apodTitle: '每日天文图',
    epicTitle: '地球多色成像相机',
    upcomingLaunch: '最近发射',
    scientificMission: '科学任务',
    goForLaunch: '准备发射',
    countdownDays: '天',
    countdownHours: '小时',
    countdownMinutes: '分',
    countdownSeconds: '秒',
    countingDown: '发射倒计时...',
    launchDataSource: '数据来源: Launch Library API →',
    issTrackerTitle: '国际空间站实时追踪',
    issActive: '活跃',
    issMapUnavailable: '地图不可用',
    issUpdateInterval: '每 5 秒自动更新一次',
    activeAstronauts: '当前在轨人员',
    astronautSub: '活跃的宇航员、航天员',
    viewAllAstronauts: '👨‍🚀 查看所有宇航员资料 →',
    astronautDataSource: '数据来源: 内部数据与 Open Notify →',
    donationEmailAlert: '请先输入您的电子邮箱以获取捐助凭证。',
    donationSuccessAlert: '捐助成功！感谢您的支持。',
    donationPendingAlert: '付款挂起，请完成您的付款。',
    donationFailAlert: '捐助付款失败。',
    donationStartFailAlert: '启动捐助付款失败。请重试。',
    dataAttribution: '🛰️ 数据属性:',
    dataProvidedBy: '本网站的数据由以下机构提供',
    freeToUse: '根据以下条款免费使用',
    nasaPolicy: 'NASA 政策',
    photoCopyrightNote: 'APOD 照片版权归 NASA 指定的各自所有者所有。',
    glossaryTitle: '多语言科学术语表',
    glossaryDescription: '气象、地球物理、天文和太空任务术语字典，帮助读者理解小雨、kosame、NEO、APOD、火星日和太空天气等技术词汇。',
    glossaryBadge: 'BMKG + NASA',
    openGlossary: '打开术语表',
    backToGlossary: '← 返回术语表',
    definitionLabel: '定义',
    exampleLabel: '例子',
    richDiscussion: '科学讨论',
    translationsLabel: '翻译',
    updatedAtLabel: '更新于：',
    sourceLabel: '来源：',
    glossaryError: '未找到术语。',
    // FireballEonetSection
    earthMonitorBadge: '🌍 从太空监测地球',
    earthMonitorTitle: '自然灾害与火球',
    earthMonitorDesc: '来自 NASA JPL 火球数据 API 和 NASA EONET 地球天文台的实时数据 — 从太空直接监测地球。',
    fireballTab: '🔥 火球',
    eonetTab: '🌍 自然事件',
    liveFireballFeed: 'JPL 实时火球数据',
    noFireballData: '暂无最新火球数据。',
    viewAllMonitoring: '在监测中心查看全部 →',
    noFireballArticles: '暂无火球文章。',
    noEonetArticles: '暂无自然事件文章。',
    autoCronFill: '每日自动定时任务将填充文章。',
    viewAllFireball: '查看全部火球文章 →',
    viewAllEonet: '查看全部自然事件文章 →',
    // List page UI
    totalArticles: '共 {n} 篇文章',
    searchFireball: '搜索火球文章...',
    searchEonet: '搜索自然事件文章...',
    searchApod: '搜索太空照片、日期或主题...',
    apodGalleryBadge: 'NASA 每日天文图 (APOD)',
    apodGalleryTitle: '太空照片画廊',
    apodGalleryDesc: '通过 NASA 官方精选天文日图探索宇宙之美，配备 AI 翻译的科学说明。',
    apodShowingOf: '显示 {filtered} / {total} 张存档照片。',
    apodNoResults: '没有符合搜索条件的太空照片。',
    viewDetail: '查看详情 →',
    readMore2: '阅读更多 →',
    fireballListBadge: '🔥 NASA/JPL 实时火球数据 API',
    fireballListTitle: '火球报告',
    fireballListDesc: '关于火球事件的科普分析 — 根据 NASA/JPL 全球红外传感器数据检测到进入地球大气层的流星火球。',
    noFireballArticlesList: '暂无火球文章',
    noFireballCron: '请使用 Admin 菜单触发火球文章自动发布。',
    noFireballMatch: '没有符合搜索条件的文章。',
    kometListBadge: '☄️ 教育与太空岩石新闻',
    kometListTitle: '彗星与小行星文章',
    kometListDesc: '科普分析、NASA NeoWs 近地天体追踪，以及实时小行星教育文章。',
    noKometArticlesList: '暂无彗星与小行星文章',
    noKometCron: '请使用 Admin 菜单触发彗星文章自动发布。',
    noKometMatch: '没有符合搜索条件的文章。',
    eonetListBadge: '🌍 NASA EONET v3 地球天文台实时数据',
    eonetListTitle: '活跃自然事件',
    eonetListDesc: '监测地球上正在发生的自然事件 — 火山、野火、强风暴及其他 NASA 从太空追踪的自然现象。',
    noEonetArticlesList: '暂无自然事件文章',
    noEonetCron: '请使用 Admin 菜单触发 EONET 文章自动发布。',
    noEonetMatch: '没有符合搜索条件的文章。',
    blogListTitle: '天文与陨石博客',
    blogListDesc: '最新科学新闻、天石识别指南和有趣的天文知识。',
    // ArticleActions
    ttsPlay: '🔊 播放 AI 语音',
    ttsStop: '⏹️ 停止语音',
    downloadPdf: '📥 下载 PDF',
    downloadShareCard: '📸 下载分享卡',
    shareLabel: '分享：',
    copyLink: '🔗 复制',
    linkCopied: '文章链接复制成功！',
    // Article back nav
    backToBlog: '← 返回文章列表',
    backToFireball: '← 返回火球',
    backToEonet: '← 返回自然事件',
    backToKomet: '← 返回彗星文章',
    backToMars: '← 返回火星文章',
    backToApod: '← 返回 APOD 画廊',
    releaseDate: '发布日期',
    copyrightLabel: '版权 / 来源',
    scientificExplanation: '科学解释',
    originalExplanation: '英文原版解释',
    apodError: '未找到太空照片或日期格式不正确。',
    backToAstronaut: '← 返回宇航员资料',
    astroError: '未找到宇航员资料。',
    astroStatusActive: '执行任务中',
    astroStatusUpcoming: '未来任务',
    astroStatusReturned: '已返回',
    astroCountry: '国家/地区',
    astroAgency: '航天机构',
    astroMissionDuration: '任务时长',
    astroUpcomingText: '已计划',
    daysUnit: '天',
    astroBioTitle: '生平与任务',
    meteorError: '未找到陨石数据。',
    backToCatalog: '返回目录',
    backToEncyclopedia: '← 返回百科目录',
    physicalSpec: '物理规格',
    rockName: '岩石名称：',
    rockType: '类型 / 类别：',
    estimatedMass: '预估质量：',
    foundYear: '发现年份：',
    latitudeLabel: '纬度坐标：',
    longitudeLabel: '经度坐标：',
    descriptionHistory: '描述与历史分析',
    landingLocation: '地理降落位置',
    impactCoordinates: '坠落坐标：',
    openInGoogleMaps: '在 Google 地图打开 →',
    articleNotFound: '文章未找到。',
    visitWebsite: '访问我们的网站',
    // Star Map / Langit Malam
    starMapBadge: '🌠 互动星图',
    starMapTitle: '夜空',
    starMapSubtitle: '允许GPS位置访问或选择您的城市，以动态导航今晚的星空星座图。',
    gpsDetecting: '正在定位...',
    gpsDetected: 'GPS已定位:',
    useGpsBtn: '📍 使用我的GPS位置',
    gpsNotSupported: '您的浏览器不支持GPS。',
    gpsErrorDenied: 'GPS访问被拒绝或不可用。请手动选择城市。',
    orSelectCity: '或选择城市',
    orManualInput: '或手动输入',
    latLabel: '纬度',
    lonLabel: '经度',
    latPlaceholder: '例如: -6.2088',
    lonPlaceholder: '例如: 106.8456',
    latError: '纬度必须是介于 -90 到 90 之间的数字。',
    lonError: '经度必须是介于 -180 到 180 之间的数字。',
    applyCoordsBtn: '应用自定义坐标',
    nightSkyAt: '今晚夜空在',
    openFullScreen: '全屏打开 ↗',
    starMapProvidedBy: '星图提供商',
    starMapInstructions: '🖱️ 点击并拖动以旋转天空 • 滚动缩放',
    constellationTitle: '今晚星座',
    constellationDesc: '根据实时位置和时间，识别今晚从您的城市可见的星座。',
    moonPhaseTitle: '月相',
    moonPhaseDesc: '监测今天的月相并预测即将到来的月相，以进行最佳的天文观测规划。',
    visiblePlanetsTitle: '可见行星',
    visiblePlanetsDesc: '了解今晚从您的位置用肉眼或望远镜可以看到哪些行星。',
    earthMonitorWidget: '夜空社区的地球实时数据',
    earthMonitorSubtitle: '地球监测模拟器',
    tabQuake: '🌋 最新地震',
    tabWeather: '🌧️ 天气与降雨',
    tabEnergy: '☀️ 风能与太阳能',
    quakePanelSub: 'BMKG TEWS 实时 JSON',
    quakePanelTitle: '最新地震动态',
    quakeRefreshTitle: '刷新 BMKG 数据',
    quakeMagnitude: '震级',
    quakeDepth: '震源深度',
    quakeRegion: '地区',
    quakeTsunami: '海啸风险',
    quakeLoadingRegion: '正在加载区域数据...',
    quakeUpdate: '更新时间:',
    quakeIndependent: '独立获取自 BMKG。',
    weatherSub: '实时天气数据',
    weatherTitle: '天气与观测条件',
    weatherGpsDetecting: '正在通过 GPS/Wi-Fi 自动检测您的位置...',
    weatherGpsFound: '已检测到位置:',
    weatherGpsDenied: '位置权限被拒绝，请使用下方手动搜索。',
    weatherGpsError: '自动定位失败，请尝试手动搜索。',
    weatherOwLoading: '正在从 OpenWeather 获取实时天气数据...',
    weatherOwActual: '🌤️ OpenWeather — 实时数据',
    weatherOwError: 'OpenWeather 暂不可用。',
    weatherOwCacheNote: '数据来源：OpenWeather API · 缓存 15 分钟',
    weatherSearchLabel: '搜索地区、城市、村庄或坐标',
    weatherSearchPlaceholder: '北京, -6.2088, 106.8456',
    weatherSearchBtn: '搜索',
    weatherSearchHint: '输入地区名、街道、村庄、城市或经纬度坐标。',
    weatherSearchMin: '请输入至少 3 个字符或完整坐标。',
    weatherSearchSuccess: '{label} 的实时数据已加载。',
    weatherSearchFail: '无法找到该位置。',
    weatherSimResult: '搜索结果 — BMKG 模拟器',
    weatherTemp: '温度',
    weatherRain: '降雨',
    weatherHumidity: '湿度',
    weatherCondition: '天气状况',
    weatherRainChance: '降雨概率',
    weatherPrecipitation: '降水量',
    weatherFeelsLike: '体感温度',
    weatherHumidityLabel: '湿度',
    weatherWind: '风速',
    weatherClouds: '云量',
    weatherHumidityHigh: '潮湿',
    weatherHumidityNormal: '正常',
    weatherHumidityLow: '干燥',
    weatherCloudsLow: '晴天',
    weatherCloudsMid: '多云',
    weatherCloudsHigh: '阴天',
    weatherTempCold: '凉爽',
    weatherTempNormal: '正常',
    weatherTempHot: '炎热',
    weatherRainLow: '低',
    weatherRainMid: '中等',
    weatherRainHigh: '高',
    weatherIntensity: '降雨强度',
    weatherCityTonight: '{city} 今晚气温:',
    energySub: 'RE-Atlas 潜力模拟器',
    energyTitle: '风能与太阳能',
    energyGpsFound: '已自动检测到位置:',
    energyGpsDenied: '位置权限被拒绝，请使用下方手动搜索。',
    energyGpsError: '自动定位失败，请尝试手动搜索。',
    energyRealtimeResult: '实时搜索结果',
    energyWind10m: '10米高度风速',
    energyWindDir: '风向',
    energySolar: '太阳辐射',
    energySolarNote: '这是来自 Open-Meteo 的实时地表气象数据，可作为当地风能和太阳能条件的初步参考。',
    energySolarLabel: '太阳能',
    energyWindLabel: '风能',
    energyTopSolar: '太阳辐射:',
    earthDataSource: '实时数据由 BMKG、Open-Meteo 和 ESDM RE-Atlas 提供，该组件独立运行，不依赖 NASA_API_KEY。',
    pushTitle: '实时太空通知',
    pushDesc: '启用浏览器通知，获取近地小行星飞掠、BMKG 地震和 NASA APOD 每日天文图的实时信息。',
    pushDismiss: '稍后再说',
    pushAccept: '启用',
    pushLoading: '正在启用...',
    astroLiveArchive: '实时与任务档案',
    astroPageTitle: '人类在太空数据库',
    astroPageDesc1: '本页面分三组概述了宇航员、航天员和太空飞行员的档案。',
    astroPageDesc2: '在轨宇航员通常在国际空间站或天宫空间站生活数月，进行微重力实验。',
    astroTotalProfiles: '总档案数',
    astroActive: '在轨',
    astroUpcomingStat: '待发射',
    astroAlumni: '已返回',
    astroTabActive: '在轨航天员',
    astroTabActiveTitle: '正在执行任务的航天员',
    astroTabActiveDesc: '目前在地球轨道执行任务的宇航员、航天员及太空飞行员。',
    astroTabUpcoming: '待发射任务',
    astroTabUpcomingTitle: '计划发射的航天员',
    astroTabUpcomingDesc: '计划执行未来飞往空间站或探索任务的航天员。',
    astroTabReturned: '太空英雄',
    astroTabReturnedTitle: '退役及已返回的航天员',
    astroTabReturnedDesc: '曾在国际空间站、天宫空间站或其他轨道任务中服役并已安全返回地球的航天员档案。',
    astroNoData: '此类别下暂无数据。',
    readFullBio: '查看完整传记',
    updatedAt: '更新时间',
    missionLabel: '任务',
  },
  ja: {
    loading: '読み込み中...',
    readMore: '続きを読む',
    readDetail: '詳細を見る',
    previous: '前へ',
    next: '次へ',
    page: 'ページ',
    all: 'すべて',
    total: '打上げ合計',
    article: '記事',
    statsMeteorites: '世界で記録された隕石',
    statsCollectors: 'インドネシアのコレクター',
    statsAsteroids: '本日の地球近傍小惑星',
    statsAstronauts: '現在軌道上の宇宙飛行士',
    objectUnit: '天体',
    crewUnit: 'クルー',
    dailyUpdate: '毎日更新',
    skyObjectToday: '今日の天体',
    nasaDailyData: 'NASA ライブデータ - 毎日更新',
    latestEarthPhoto: '最新の地球写真を読み込み中...',
    epicUnavailable: 'EPIC の地球写真は現在利用できません',
    epicMonitor: 'EPIC 衛星モニター',
    epicDescription: 'NASA EPIC が 150 万 km 離れた場所から撮影した最新の地球写真で、太陽に照らされた地球の面を示しています。',
    latitude: '緯度',
    longitude: '経度',
    latest: '最新',
    monitorEpic: 'EPIC を見る',
    viewAllMeteorCatalog: '隕石カタログをすべて見る',
    blogLatest: '最新の天文記事',
    newsletterTitle: 'ニュースを購読',
    newsletterDescription: 'メールを入力すると、新しい流星落下や天文記事の通知を無料で受け取れます。',
    newsletterSuccess: 'ありがとうございます！ニュースレターに登録されました。',
    emailPlaceholder: 'メールアドレスを入力',
    subscribeNow: '今すぐ購読',
    blogTitle: '天文・隕石ブログ',
    blogDescription: '最新の科学ニュース、空の石の識別ガイド、興味深い天文トリビア。',
    searchScience: '科学記事を検索...',
    noArticles: '記事はまだありません',
    noGeneratedArticles: 'AI 記事はまだ生成されていません。Admin - Article Management - Create AI Article をクリックしてください。',
    noSearchMatch: '検索に一致する記事はありません。',
    cometBadge: '宇宙岩石ニュースと教育',
    cometTitle: '彗星・小惑星の記事',
    cometDescription: '一般向け科学解説、NASA NeoWs の地球近傍天体追跡、リアルタイム小惑星教育記事。',
    searchComet: '彗星・小惑星の記事を検索...',
    noCometArticles: '彗星・小惑星の記事はまだありません',
    noCometGenerated: 'Admin メニューから彗星記事の自動公開を実行してください。',
    redPlanet: '赤い惑星',
    marsLatest: '最新の火星記事',
    marsDescription: 'Meteorit Indonesia の記事アーカイブから、ローバー、地質、極端な気象、人類の火星での未来を紹介します。',
    viewAllMars: '火星記事をすべて見る',
    readMars: '火星記事を読む',
    communityTitle: '隕石かどうか？',
    communityP1: '屋外で珍しい石を見つけ、それが普通の地球の岩石か宇宙から来た隕石か迷っていますか？',
    communityP2: '発見した石の写真をフォーラムにアップロードし、天文学の専門家やコミュニティに投票形式で評価してもらいましょう。',
    askForum: 'フォーラムで質問',
    welcome: 'ようこそ',
    forumVisit: 'ディスカッションフォーラムで質問を書く',
    googleLoginPrompt: '参加するには Google でログイン',
    googleLogin: 'Google でログイン',
    donationTitle: '科学探索とコミュニティを支援',
    donationDescription: 'Meteorit Indonesia はコミュニティに支えられた非営利プラットフォームです。寄付はホスティング、NASA API、宇宙教育研究の開発に使われます。',
    donationStepEmail: 'ステップ 1: メールアドレスを入力',
    donationStepAmount: 'ステップ 2: 寄付額を選択',
    donationCustom: '任意の寄付額を入力',
    donationButton: 'Midtrans で寄付',
    donationProcessing: '支払い処理中...',
    liveSpaceData: 'ライブ宇宙データ',
    missionControlTitle: '宇宙ミッション管制',
    missionControlDesc: '地球軌道ミッションと宇宙ステーションのリアルタイムデータ',
    
    // New Translations
    nasaApodLabel: '📡 NASA APOD',
    nasaEpicLabel: '🌍 NASA EPIC',
    apodTitle: '今日の天文画像',
    epicTitle: '地球多色画像カメラ',
    upcomingLaunch: '次の打上げ',
    scientificMission: '科学ミッション',
    goForLaunch: '打上げ準備完了',
    countdownDays: '日',
    countdownHours: '時間',
    countdownMinutes: '分',
    countdownSeconds: '秒',
    countingDown: 'カウントダウン中...',
    launchDataSource: 'データソース: Launch Library API →',
    issTrackerTitle: 'ライブISSトラッカー',
    issActive: 'アクティブ',
    issMapUnavailable: '地図は利用できません',
    issUpdateInterval: '5秒ごとに自動更新されます',
    activeAstronauts: '現在軌道上のクルー',
    astronautSub: 'アクティブな宇宙飛行士、宇宙飛行士',
    viewAllAstronauts: '👨‍🚀 すべての宇宙飛行士を見る →',
    astronautDataSource: 'データソース: 内部データと Open Notify →',
    donationEmailAlert: '寄付の領収書を受け取るために、まずメールアドレスを入力してください。',
    donationSuccessAlert: '寄付が成功しました！ご支援ありがとうございます。',
    donationPendingAlert: 'お支払いは保留中です。お支払いを完了してください。',
    donationFailAlert: '寄付の支払いに失敗しました。',
    donationStartFailAlert: '寄付の支払いを開始できませんでした。もう一度お試しください。',
    dataAttribution: '🛰️ データ属性:',
    dataProvidedBy: 'このサイトのデータは以下によって提供されています',
    freeToUse: '以下に従って無料で使用できます',
    nasaPolicy: 'NASA 方針',
    photoCopyrightNote: 'APOD写真の著作権は、NASAの指定に従ってそれぞれの所有者に帰属します。',
    glossaryTitle: '多言語科学用語集',
    glossaryDescription: '小雨、kosame、NEO、APOD、火星日、宇宙天気などの専門用語を読者が理解するのに役立つ、気象学、地球物理学、天文学、宇宙ミッションの用語集。',
    glossaryBadge: 'BMKG + NASA',
    openGlossary: '用語集を開く',
    backToGlossary: '← 用語集に戻る',
    definitionLabel: '定義',
    exampleLabel: '例',
    richDiscussion: '科学的解説',
    translationsLabel: '翻訳',
    updatedAtLabel: '更新日：',
    sourceLabel: '情報源：',
    glossaryError: '用語が見つかりません。',
    // FireballEonetSection
    earthMonitorBadge: '🌍 宇宙からの地球監視',
    earthMonitorTitle: '自然災害と火球',
    earthMonitorDesc: 'NASA JPL 火球データ API と NASA EONET 地球天文台からのリアルタイムデータ — 宇宙から直接地球を監視。',
    fireballTab: '🔥 火球',
    eonetTab: '🌍 自然現象',
    liveFireballFeed: 'JPL リアルタイム火球フィード',
    noFireballData: '最新の火球データはありません。',
    viewAllMonitoring: '監視センターで全て見る →',
    noFireballArticles: '火球の記事はまだありません。',
    noEonetArticles: '自然現象の記事はまだありません。',
    autoCronFill: '毎日の自動スケジュールが記事を更新します。',
    viewAllFireball: '全ての火球記事を見る →',
    viewAllEonet: '全ての自然現象記事を見る →',
    // List page UI
    totalArticles: '合計: {n} 記事',
    searchFireball: '火球記事を検索...',
    searchEonet: '自然現象記事を検索...',
    searchApod: '宇宙写真、日付、またはトピックを検索...',
    apodGalleryBadge: 'NASA 今日の天文写真 (APOD)',
    apodGalleryTitle: '宇宙写真ギャラリー',
    apodGalleryDesc: 'NASA 公式の天文日写真を通じて宇宙の美しさを探索し、AI 翻訳による科学的解説も掲載。',
    apodShowingOf: '{filtered} / {total} 枚のアーカイブ写真を表示中。',
    apodNoResults: '検索に一致する宇宙写真はありません。',
    viewDetail: '詳細を見る →',
    readMore2: '続きを読む →',
    fireballListBadge: '🔥 NASA/JPL リアルタイム火球データ API',
    fireballListTitle: '火球レポート',
    fireballListDesc: '火球イベントの科学的分析 — NASA/JPL グローバル赤外センサーデータに基づいて地球の大気に入る流星火球を検出。',
    noFireballArticlesList: '火球記事はまだありません',
    noFireballCron: 'Admin メニューで火球記事の自動公開を実行してください。',
    noFireballMatch: '検索に一致する記事はありません。',
    kometListBadge: '☄️ 宇宙岩石ニュースと教育',
    kometListTitle: '彗星・小惑星の記事',
    kometListDesc: '一般向け科学解説、NASA NeoWs 地球近傍天体追跡、リアルタイム小惑星教育記事。',
    noKometArticlesList: '彗星・小惑星の記事はまだありません',
    noKometCron: 'Admin メニューから彗星記事の自動公開を実行してください。',
    noKometMatch: '検索に一致する記事はありません。',
    eonetListBadge: '🌍 NASA EONET v3 地球天文台リアルタイムデータ',
    eonetListTitle: '活発な自然現象',
    eonetListDesc: '地球で起きている自然現象を監視 — 火山、山火事、大型嵐、そして NASA が宇宙から追跡する自然現象。',
    noEonetArticlesList: '自然現象記事はまだありません',
    noEonetCron: 'Admin メニューから EONET 記事の自動公開を実行してください。',
    noEonetMatch: '検索に一致する記事はありません。',
    blogListTitle: '天文・隕石ブログ',
    blogListDesc: '最新の科学ニュース、空の石の識別ガイド、興味深い天文トリビア。',
    // ArticleActions
    ttsPlay: '🔊 AI 音声を再生',
    ttsStop: '⏹️ 音声を停止',
    downloadPdf: '📥 PDF をダウンロード',
    downloadShareCard: '📸 シェアカードをダウンロード',
    shareLabel: 'シェア：',
    copyLink: '🔗 コピー',
    linkCopied: '記事リンクをコピーしました！',
    // Article back nav
    backToBlog: '← 記事一覧に戻る',
    backToFireball: '← 火球に戻る',
    backToEonet: '← 自然現象に戻る',
    backToKomet: '← 彗星記事に戻る',
    backToMars: '← 火星記事に戻る',
    backToApod: '← APOD ギャラリーに戻る',
    releaseDate: '公開日',
    copyrightLabel: '著作権 / 情報源',
    scientificExplanation: '科学的な解説',
    originalExplanation: '原文（英語）解説',
    apodError: '宇宙写真が見つからないか、日付の形式が正しくありません。',
    backToAstronaut: '← 宇宙飛行士プロフィールに戻る',
    astroError: '宇宙飛行士のプロフィールが見つかりません。',
    astroStatusActive: 'ミッション中',
    astroStatusUpcoming: '次回ミッション',
    astroStatusReturned: '帰還済み',
    astroCountry: '国籍',
    astroAgency: '宇宙機関',
    astroMissionDuration: 'ミッション期間',
    astroUpcomingText: '予定通り',
    daysUnit: '日',
    astroBioTitle: '経歴とミッション',
    meteorError: '隕石データが見つかりません。',
    backToCatalog: 'カタログに戻る',
    backToEncyclopedia: '← 百科事典カタログに戻る',
    physicalSpec: '物理仕様',
    rockName: '岩石名：',
    rockType: '分類 / クラス：',
    estimatedMass: '推定質量：',
    foundYear: '発見年：',
    latitudeLabel: '纬度座標：',
    longitudeLabel: '经度座標：',
    descriptionHistory: '記述と歴史的分析',
    landingLocation: '地理的落下位置',
    impactCoordinates: '落下座標：',
    openInGoogleMaps: 'Google マップで開く →',
    articleNotFound: '記事が見つかりません。',
    visitWebsite: '私たちのサイトを訪問',
    // Star Map / Langit Malam
    starMapBadge: '🌠 インタラクティブ星図',
    starMapTitle: '星空',
    starMapSubtitle: 'GPS位置情報アクセスを許可するか、都市を選択して、今夜の星座マップを動的に移動します。',
    gpsDetecting: '位置検出中...',
    gpsDetected: 'GPS検出完了:',
    useGpsBtn: '📍 GPS位置情報を使用する',
    gpsNotSupported: 'お使いのブラウザはGPSに対応していません。',
    gpsErrorDenied: 'GPSアクセスが拒否されたか、利用できません。都市を手動で選択してください。',
    orSelectCity: 'または都市を選択',
    orManualInput: 'または手動入力',
    latLabel: '緯度',
    lonLabel: '経度',
    latPlaceholder: '例: -6.2088',
    lonPlaceholder: '例: 106.8456',
    latError: '緯度は-90から90の間の数値である必要があります。',
    lonError: '経度は-180から180の間の数値である必要があります。',
    applyCoordsBtn: 'カスタム座標を適用',
    nightSkyAt: '今夜の星空：',
    openFullScreen: '全画面で開く ↗',
    starMapProvidedBy: '星図提供：',
    starMapInstructions: '🖱️ クリック＆ドラッグで回転 • スクロールでズーム',
    constellationTitle: '今夜の星座',
    constellationDesc: 'リアルタイムの位置と時間に基づいて、今夜あなたの都市から見える星座を特定します。',
    moonPhaseTitle: '月齢・月相',
    moonPhaseDesc: '今日の月相を監視し、天体観測計画に最適な次の月相を予測します。',
    visiblePlanetsTitle: '見える惑星',
    visiblePlanetsDesc: '今夜あなたの位置から肉眼または望遠鏡で見える惑星を特定します。',
    earthMonitorWidget: '夜空コミュニティのための地球リアルタイムデータ',
    earthMonitorSubtitle: '地球モニタリングシミュレーター',
    tabQuake: '🌋 最新地震',
    tabWeather: '🌧️ 天気・降雨',
    tabEnergy: '☀️ 風力・太陽光',
    quakePanelSub: 'BMKG TEWS ライブJSON',
    quakePanelTitle: '最新地震情報',
    quakeRefreshTitle: 'BMKGデータを更新',
    quakeMagnitude: 'マグニチュード',
    quakeDepth: '震源深さ',
    quakeRegion: '地域',
    quakeTsunami: '津波の可能性',
    quakeLoadingRegion: '地域データを読み込み中...',
    quakeUpdate: '更新:',
    quakeIndependent: 'BMKGから独立して取得。',
    weatherSub: 'リアルタイム気象データ',
    weatherTitle: '天気と観測コンディション',
    weatherGpsDetecting: 'GPS/Wi-Fiで現在地を自動検出中...',
    weatherGpsFound: '検出された場所:',
    weatherGpsDenied: '位置情報の許可が拒否されました。下の手動検索をご利用ください。',
    weatherGpsError: '自動位置検出に失敗しました。手動で検索してください。',
    weatherOwLoading: 'OpenWeatherから実際の気象データを取得中...',
    weatherOwActual: '🌤️ OpenWeather — リアルタイムデータ',
    weatherOwError: 'OpenWeatherは利用できません。',
    weatherOwCacheNote: 'データソース: OpenWeather API · 15分キャッシュ',
    weatherSearchLabel: '地区、都市、村、または座標を検索',
    weatherSearchPlaceholder: '東京, -6.2088, 106.8456',
    weatherSearchBtn: '検索',
    weatherSearchHint: '地区名、道路、村、市区町村、都市、または緯度・経度座標を入力してください。',
    weatherSearchMin: '3文字以上または完全な座標を入力してください。',
    weatherSearchSuccess: '{label} のリアルタイムデータを読み込みました。',
    weatherSearchFail: '場所が見つかりませんでした。',
    weatherSimResult: '検索結果 — BMKGシミュレーター',
    weatherTemp: '気温',
    weatherRain: '降雨',
    weatherHumidity: '湿度',
    weatherCondition: '天気状態',
    weatherRainChance: '降水確率',
    weatherPrecipitation: '降水量',
    weatherFeelsLike: '体感温度',
    weatherHumidityLabel: '湿度',
    weatherWind: '風速',
    weatherClouds: '雲量',
    weatherHumidityHigh: '多湿',
    weatherHumidityNormal: '普通',
    weatherHumidityLow: '乾燥',
    weatherCloudsLow: '晴れ',
    weatherCloudsMid: '曇り',
    weatherCloudsHigh: '曇天',
    weatherTempCold: '涼しい',
    weatherTempNormal: '普通',
    weatherTempHot: '暑い',
    weatherRainLow: '低',
    weatherRainMid: '中程度',
    weatherRainHigh: '高',
    weatherIntensity: '雨の強さ',
    weatherCityTonight: '{city} 今夜の気温:',
    energySub: 'RE-Atlasポテンシャルシミュレーター',
    energyTitle: '風力・太陽光エネルギー',
    energyGpsFound: '場所を自動検出しました:',
    energyGpsDenied: '位置情報の許可が拒否されました。下の手動検索をご利用ください。',
    energyGpsError: '自動位置検出に失敗しました。手動で検索してください。',
    energyRealtimeResult: 'リアルタイム検索結果',
    energyWind10m: '高度10m風速',
    energyWindDir: '風向',
    energySolar: '太陽放射',
    energySolarNote: 'これはOpen-Meteoのリアルタイム地上気象データであり、現地の風力・太陽光条件の初期指標として利用できます。',
    energySolarLabel: '太陽光',
    energyWindLabel: '風力',
    energyTopSolar: '太陽放射量:',
    earthDataSource: 'ライブデータはBMKG、Open-Meteo、ESDM RE-Atlasが提供しています。このウィジェットはNASA_API_KEYとは独立して動作します。',
    pushTitle: 'リアルタイム宇宙通知',
    pushDesc: 'ブラウザ通知をオンにして、小惑星の接近、BMKGの地震情報、NASA APODギャラリーのライブ通知を受け取りましょう。',
    pushDismiss: '後で',
    pushAccept: 'オンにする',
    pushLoading: '設定中...',
    astroLiveArchive: 'ライブ＆ミッションアーカイブ',
    astroPageTitle: '宇宙飛行士データベース',
    astroPageDesc1: 'このページでは、宇宙飛行士、宇宙飛行関係者のプロファイルを3つのグループに分類して紹介します。',
    astroPageDesc2: '現役クルーは通常、ISSまたは天宮で数ヶ月間過ごし、微小重力実験や軌道運用を行います。',
    astroTotalProfiles: 'プロファイル総数',
    astroActive: 'ミッション中',
    astroUpcomingStat: '予定',
    astroAlumni: '帰還済',
    astroTabActive: '現在宇宙にいるクルー',
    astroTabActiveTitle: '現在任務中のクルー',
    astroTabActiveDesc: '現在、地球軌道上でアクティブなミッションに従事している宇宙飛行士および宇宙飛行関係者。',
    astroTabUpcoming: '今後のミッション',
    astroTabUpcomingTitle: '打ち上げ予定のクルー',
    astroTabUpcomingDesc: '宇宙ステーションまたは探査ミッションへの参加が予定されているクルー。',
    astroTabReturned: '宇宙の英雄',
    astroTabReturnedTitle: 'アルムナイおよび帰還クルー',
    astroTabReturnedDesc: 'ISS、天宮、またはその他の軌道ミッションに従事し、地球に帰還したクルーのアーカイブ。',
    astroNoData: 'このカテゴリのデータはありません。',
    readFullBio: '詳細な経歴を見る',
    updatedAt: '更新日',
    missionLabel: 'ミッション',
  },
};

export const landingText: Record<SiteLanguage, Record<string, string>> = {
  ...landingTextBase,
  ru: landingTextRu,
  fr: landingTextFr
};
